import type { FeatureDefinition } from "./contracts"

export const featureDefinitions: readonly FeatureDefinition[] = [
  {
    key: "hrm-basic",
    name: "HRM Basic",
    module: "HRM",
    description: "Core HR, attendance, and leave management.",
    enabledTiers: ["basic", "pro", "enterprise"],
    isEnabled: true,
  },
  {
    key: "crm-basic",
    name: "CRM Basic",
    module: "CRM",
    description: "Customer management, contacts, and sales pipeline.",
    enabledTiers: ["basic", "pro", "enterprise"],
    isEnabled: true,
  },
  {
    key: "pm",
    name: "Project Management",
    module: "PM",
    description: "Projects, tasks, and execution tracking.",
    enabledTiers: ["basic", "pro", "enterprise"],
    isEnabled: true,
  },
  {
    key: "excel-ai",
    name: "ExcelAI",
    module: "ExcelAI",
    description: "AI-assisted spreadsheet and CSV workflows.",
    enabledTiers: ["basic", "pro", "enterprise"],
    isEnabled: true,
  },
  {
    key: "mrp",
    name: "MRP",
    module: "MRP",
    description: "Manufacturing, BOM, inventory, and production controls.",
    enabledTiers: ["pro", "enterprise"],
    isEnabled: true,
  },
  {
    key: "otb",
    name: "Order to Bill",
    module: "OTB",
    description: "Order, invoice, and payment workflow management.",
    enabledTiers: ["pro", "enterprise"],
    isEnabled: true,
  },
  {
    key: "accounting-vas",
    name: "Accounting VAS",
    module: "ACC",
    description: "Vietnam accounting workflows and compliance support.",
    enabledTiers: ["pro", "enterprise"],
    isEnabled: true,
  },
  {
    key: "tpm",
    name: "Trade Promotion",
    module: "TPM",
    description: "Trade promotion budget, claims, and commercial workflows.",
    enabledTiers: ["pro", "enterprise"],
    isEnabled: true,
  },
  {
    key: "hrm-advanced",
    name: "HRM Advanced",
    module: "HRM",
    description: "Payroll, document generation, and advanced HR workflows.",
    enabledTiers: ["pro", "enterprise"],
    isEnabled: true,
  },
  {
    key: "crm-advanced",
    name: "CRM Advanced",
    module: "CRM",
    description: "Segmentation, automation, and advanced CRM analytics.",
    enabledTiers: ["pro", "enterprise"],
    isEnabled: true,
  },
  {
    key: "ai-copilot",
    name: "AI Copilot",
    module: "AI",
    description: "AI copilots, automation, and predictive assistance.",
    enabledTiers: ["enterprise"],
    isEnabled: true,
  },
  {
    key: "accounting-ifrs",
    name: "Accounting IFRS",
    module: "ACC",
    description: "Parallel IFRS accounting and enterprise reporting support.",
    enabledTiers: ["enterprise"],
    isEnabled: true,
  },
  {
    key: "ecommerce",
    name: "E-Commerce",
    module: "ECOM",
    description: "Omnichannel commerce and marketplace integration support.",
    enabledTiers: ["enterprise"],
    isEnabled: true,
  },
  {
    key: "custom-sdk",
    name: "Custom SDK",
    module: "SDK",
    description: "Extended integration surface, SDK, and webhook support.",
    enabledTiers: ["enterprise"],
    isEnabled: true,
  },
  {
    key: "multi-tenant",
    name: "Multi-Tenant",
    module: "INFRA",
    description: "Advanced tenant isolation and infrastructure controls.",
    enabledTiers: ["enterprise"],
    isEnabled: true,
  },
]

export const FEATURE_REGISTRY = new Map<string, FeatureDefinition>(
  featureDefinitions.map((feature) => [feature.key, feature])
)
