import type { ErpModuleMetadata } from "../contract/erp-module-catalog.contract"

export const erpModuleCatalog: readonly ErpModuleMetadata[] = [
  {
    moduleId: "dashboard",
    routeId: "dashboard",
    pathSegment: "dashboard",
    kind: "platform-module",
    lifecycle: "enabled",
    navLabelKey: "nav.dashboard",
    titleKey: "nav.dashboard",
    groupId: "workspace",
    permissionKeys: [],
    legacyReferencePaths: [".legacy/cna-templates/packages/dashboard"],
  },
  {
    moduleId: "events",
    routeId: "events",
    pathSegment: "events",
    kind: "erp-module",
    lifecycle: "enabled",
    navLabelKey: "nav.items.events",
    titleKey: "breadcrumb.events",
    groupId: "workspace",
    permissionKeys: ["ops:event:view"],
    legacyReferencePaths: [".legacy/cna-templates/packages/events"],
  },
  {
    moduleId: "audit",
    routeId: "audit",
    pathSegment: "audit",
    kind: "platform-module",
    lifecycle: "enabled",
    navLabelKey: "nav.items.audit",
    titleKey: "breadcrumb.audit",
    groupId: "workspace",
    permissionKeys: ["ops:audit:view"],
    legacyReferencePaths: [".legacy/cna-templates/packages/audit"],
  },
  {
    moduleId: "counterparties",
    routeId: "counterparties",
    pathSegment: "counterparties",
    kind: "erp-module",
    lifecycle: "enabled",
    navLabelKey: "nav.items.counterparties",
    titleKey: "breadcrumb.counterparties",
    groupId: "workspace",
    permissionKeys: ["mdm:counterparty:view"],
    legacyReferencePaths: [".legacy/cna-templates/packages/master-data"],
  },
  {
    moduleId: "db-studio",
    routeId: "db-studio",
    pathSegment: "db-studio",
    kind: "platform-module",
    lifecycle: "enabled",
    navLabelKey: "nav.items.db_studio",
    titleKey: "breadcrumb.db_studio",
    groupId: "workspace",
    permissionKeys: ["admin:workspace:manage"],
  },
  {
    moduleId: "settings-account",
    routeId: "settings-account",
    pathSegment: "settings/account",
    kind: "settings-module",
    lifecycle: "enabled",
    navLabelKey: "user_menu.account",
    titleKey: "breadcrumb.account",
    groupId: "workspace",
    permissionKeys: [],
  },
  {
    moduleId: "settings-security",
    routeId: "settings-security",
    pathSegment: "settings/security",
    kind: "settings-module",
    lifecycle: "enabled",
    navLabelKey: "auth_security.panel_title",
    titleKey: "breadcrumb.security",
    groupId: "workspace",
    permissionKeys: [],
  },
  {
    moduleId: "finance-accounting",
    routeId: "finance-accounting",
    pathSegment: "finance",
    kind: "erp-module",
    lifecycle: "enabled",
    navLabelKey: "nav.finance",
    titleKey: "erp_module.finance.page.title",
    groupId: "workspace",
    permissionKeys: ["finance:accounting:view"],
    legacyReferencePaths: [
      ".legacy/cna-templates/apps/Accounting",
      ".legacy/cna-templates/packages/tpm-shared/src/finance-core",
    ],
  },
  {
    moduleId: "invoices",
    routeId: "invoices",
    pathSegment: "invoices",
    kind: "erp-module",
    lifecycle: "enabled",
    navLabelKey: "nav.invoices",
    titleKey: "nav.invoices",
    groupId: "workspace",
    permissionKeys: ["finance:accounting:view"],
    legacyReferencePaths: [
      ".legacy/cna-templates/apps/Accounting/src/lib/invoice-engine",
    ],
  },
  {
    moduleId: "allocations",
    routeId: "allocations",
    pathSegment: "allocations",
    kind: "erp-module",
    lifecycle: "enabled",
    navLabelKey: "finance_tabs.allocations",
    titleKey: "finance_tabs.allocations",
    groupId: "workspace",
    permissionKeys: ["finance:accounting:view"],
    legacyReferencePaths: [".legacy/cna-templates/TPM/WEEK-2-FINANCE"],
  },
  {
    moduleId: "settlements",
    routeId: "settlements",
    pathSegment: "settlements",
    kind: "erp-module",
    lifecycle: "enabled",
    navLabelKey: "finance_tabs.settlements",
    titleKey: "finance_tabs.settlements",
    groupId: "workspace",
    permissionKeys: ["finance:accounting:view"],
    legacyReferencePaths: [".legacy/cna-templates/TPM/WEEK-2-FINANCE"],
  },
  {
    moduleId: "crm-counterparties",
    routeId: "crm-counterparties",
    pathSegment: "crm",
    kind: "erp-module",
    lifecycle: "planned",
    navLabelKey: "nav.items.counterparties",
    titleKey: "breadcrumb.counterparties",
    groupId: "workspace",
    permissionKeys: ["crm:counterparty:view"],
    legacyReferencePaths: [".legacy/cna-templates/apps/CRM"],
  },
  {
    moduleId: "inventory",
    routeId: "inventory",
    pathSegment: "inventory",
    kind: "erp-module",
    lifecycle: "planned",
    navLabelKey: "nav.inventory",
    titleKey: "erp_module.inventory.page.title",
    groupId: "workspace",
    permissionKeys: ["inventory:item:view"],
    legacyReferencePaths: [".legacy/cna-templates/apps/MRP"],
  },
  {
    moduleId: "sales",
    routeId: "sales",
    pathSegment: "sales",
    kind: "erp-module",
    lifecycle: "planned",
    navLabelKey: "nav.sales",
    titleKey: "erp_module.sales.page.title",
    groupId: "workspace",
    permissionKeys: ["sales:order:view"],
    legacyReferencePaths: [
      ".legacy/cna-templates/apps/CRM",
      ".legacy/cna-templates/apps/Ecommerce",
    ],
  },
  {
    moduleId: "employees",
    routeId: "employees",
    pathSegment: "employees",
    kind: "erp-module",
    lifecycle: "planned",
    navLabelKey: "nav.employees",
    titleKey: "erp_module.employees.page.title",
    groupId: "workspace",
    permissionKeys: ["hrm:employee:view"],
    legacyReferencePaths: [
      ".legacy/cna-templates/apps/HRM",
      ".legacy/cna-templates/apps/HRM-unified",
    ],
  },
  {
    moduleId: "reports",
    routeId: "reports",
    pathSegment: "reports",
    kind: "erp-module",
    lifecycle: "planned",
    navLabelKey: "nav.reports",
    titleKey: "erp_module.reports.page.title",
    groupId: "workspace",
    permissionKeys: ["report:view"],
    legacyReferencePaths: [
      ".legacy/cna-templates/apps/Accounting/src/lib/reports",
      ".legacy/cna-templates/reports",
    ],
  },
] as const satisfies readonly ErpModuleMetadata[]
