/**
 * Generate a compact repository screening report for filesystem governance.
 * The report is intentionally human-readable so refactor work can be planned
 * from actual repo shape rather than generic preference.
 */

import { mkdirSync, writeFileSync } from "node:fs"
import path from "node:path"

import {
  evaluateFilesystemGovernance,
  loadFilesystemGovernanceConfig,
} from "../lib/filesystem-governance"

const REPORT_PATH = path.resolve(
  "rules/filesystem-governance/repo-screening.md"
)

const config = loadFilesystemGovernanceConfig()
const evaluation = evaluateFilesystemGovernance(config)
const violations = evaluation.violations

const groupedViolations = groupViolationsByRule(violations)

const lines = [
  "# Repo Screening",
  "",
  "Generated by `pnpm run script:generate-filesystem-governance-report`.",
  "",
  "## Summary",
  "",
  `- Governed roots: ${String(config.governedRoots.length)}`,
  `- Violations: ${String(violations.length)}`,
  "",
  "## Governed Roots",
  "",
  ...config.governedRoots.map((root) => {
    const normalizedRoot = root.root.replaceAll("\\", "/")
    const summary = evaluation.rootSummaries.find(
      (item) => item.root === normalizedRoot
    )

    return `- \`${root.root}\` : max depth ${String(root.maxDirectoryDepth)}, promoted shared roots [${root.allowedPromotedSharedRoots.join(", ")}], directories ${String(summary?.directoryCount ?? 0)}, files ${String(summary?.fileCount ?? 0)}, violations ${String(summary?.violationCount ?? 0)}`
  }),
  "",
  "## Violation Counts By Root",
  "",
  ...evaluation.rootSummaries.map(
    (summary) =>
      `- \`${summary.root}\`: ${String(summary.violationCount)} violation(s)`
  ),
  "",
  "## Violation Counts By Rule",
  "",
  ...Object.entries(groupedViolations).map(
    ([rule, items]) => `- \`${rule}\`: ${String(items.length)}`
  ),
  "",
  "## First Violations",
  "",
]

if (violations.length === 0) {
  lines.push("- No current violations under the scoped rollout.")
} else {
  for (const violation of violations.slice(0, 50)) {
    lines.push(`- [${violation.rule}] \`${violation.path}\``)
    lines.push(`  - ${violation.message}`)
  }
}

lines.push("", "## Notes", "")
lines.push(
  "- This report is scoped to the current rollout roots, not the entire repository."
)
lines.push(
  "- Expand the config only after the current scope remains stable and actionable."
)

mkdirSync(path.dirname(REPORT_PATH), { recursive: true })
writeFileSync(REPORT_PATH, `${lines.join("\n")}\n`, "utf8")

console.log(`Filesystem governance report written to ${REPORT_PATH}`)

function groupViolationsByRule(
  items: readonly {
    readonly rule: string
  }[]
): Readonly<Record<string, readonly { readonly rule: string }[]>> {
  const grouped = new Map<string, { readonly rule: string }[]>()

  for (const item of items) {
    const existing = grouped.get(item.rule) ?? []
    grouped.set(item.rule, [...existing, item])
  }

  return Object.fromEntries(grouped.entries())
}
