#!/usr/bin/env tsx
/**
 * Generates `icons/__*.ts` barrels under @afenda/design-system from:
 * 1. Existing exports in those files (stable baseline)
 * 2. Static scans for `<IconLucide name="…" />` (and siblings) in package-local
 *    design-system sources.
 *
 * Adapted from upstream: https://github.com/shadcn-ui/ui/blob/main/apps/v4/scripts/build-icons.ts
 */
import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

import { iconLibraries, type IconLibraryName } from '../libraries'

type IconUsage = Record<IconLibraryName, Set<string>>

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const packageRoot = path.resolve(__dirname, '../..')
const outputDir = path.join(packageRoot, 'icons')

const COMPONENT_TO_LIB = {
  IconLucide: 'lucide',
  IconTabler: 'tabler',
  IconHugeicons: 'hugeicons',
  IconPhosphor: 'phosphor',
  IconRemixicon: 'remixicon',
} as const satisfies Record<string, IconLibraryName>

function findTsxFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return []
  const files: string[] = []
  const entries = fs.readdirSync(dir, { withFileTypes: true })

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === 'dist') continue
      files.push(...findTsxFiles(fullPath))
    } else if (
      entry.isFile() &&
      (entry.name.endsWith('.tsx') || entry.name.endsWith('.ts'))
    ) {
      files.push(fullPath)
    }
  }

  return files
}

function parseExistingExportNames(filePath: string): string[] {
  if (!fs.existsSync(filePath)) return []
  const content = fs.readFileSync(filePath, 'utf-8')
  const names: string[] = []
  const re = /export\s*\{\s*([^}]+)\s*\}/g
  let m: RegExpExecArray | null
  while ((m = re.exec(content)) !== null) {
    const parts = m[1]
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
    for (const p of parts) {
      const n = p.split(/\s+as\s+/)[0]?.trim()
      if (n) names.push(n)
    }
  }
  return names
}

function scanDynamicIconUsage(content: string, iconUsage: IconUsage): void {
  for (const [component, lib] of Object.entries(COMPONENT_TO_LIB)) {
    const re = new RegExp(
      `<${component}[\\s\\S]*?\\sname=["']([^"']+)["']`,
      'g',
    )
    let match: RegExpExecArray | null
    while ((match = re.exec(content)) !== null) {
      iconUsage[lib].add(match[1])
    }
  }
}

function collectIconUsage(): IconUsage {
  const iconUsage: IconUsage = Object.keys(iconLibraries).reduce((acc, key) => {
    acc[key as IconLibraryName] = new Set<string>()
    return acc
  }, {} as IconUsage)

  for (const key of Object.keys(iconLibraries) as IconLibraryName[]) {
    const filename = `__${key}__.ts`
    const existingPath = path.join(outputDir, filename)
    for (const name of parseExistingExportNames(existingPath)) {
      iconUsage[key].add(name)
    }
  }

  const scanRoots = [
    path.join(packageRoot, 'ui-primitives'),
    path.join(packageRoot, 'utils'),
  ]

  const files: string[] = []
  for (const root of scanRoots) {
    files.push(...findTsxFiles(root))
  }

  for (const file of files) {
    const norm = file.replace(/\\/g, '/')
    if (norm.includes('/icons/__') && path.basename(file).startsWith('__')) {
      continue
    }
    if (path.basename(file).startsWith('__')) {
      continue
    }
    const content = fs.readFileSync(file, 'utf-8')
    scanDynamicIconUsage(content, iconUsage)
  }

  return iconUsage
}

function generateIconFiles(iconUsage: IconUsage): void {
  fs.mkdirSync(outputDir, { recursive: true })

  console.log('Generated icon barrels:')

  for (const [libraryName, config] of Object.entries(iconLibraries)) {
    const icons = Array.from(iconUsage[libraryName as IconLibraryName]).sort()

    if (icons.length === 0) {
      continue
    }

    const header = `// Auto-generated by packages/design-system/icons/script/build-icons.ts — run pnpm run icons:generate\n`

    const body = icons
      .map((icon) => `export { ${icon} } from '${config.export}'`)
      .join('\n')

    const filename = `__${libraryName}__.ts`
    fs.writeFileSync(path.join(outputDir, filename), `${header}\n${body}\n`)

    console.log(`  - ${config.title}: ${icons.length} icons`)
  }
}

function main(): void {
  const iconUsage = collectIconUsage()
  generateIconFiles(iconUsage)
}

main()
