/**
 * MODULE ENTRYPOINT — constant
 * Public export barrel for the governed constant layer.
 * Scope: re-exports canonical constants, policies, registries, validators, and metadata.
 * Consumption: import from this surface when the caller needs governed constant-layer APIs.
 * Boundaries: keep exports intentional so internal helpers do not become accidental public contract.
 * Changes: update canonical source files first, then keep this barrel synchronized.
 * Purpose: provide one reviewable constant-layer entry surface for consumers and tooling.
 */
export * from "./schema/shared"
export * from "./governance-version"
export * from "./rule-policy"
export * from "./validate-constants"

export * from "./foundation/accessibility"
export * from "./foundation/density"
export * from "./foundation/elevation"
export * from "./foundation/interaction"
export * from "./foundation/layout"
export * from "./foundation/motion"
export * from "./foundation/radius"
export * from "./foundation/token-contract"
export * from "./foundation/typography"

export * from "./semantic/emphasis"
export * from "./semantic/intent"
export * from "./semantic/severity"
export * from "./semantic/status"
export * from "./semantic/surface"
export * from "./semantic/tone"

export * from "./component/accordion"
export * from "./component/alert"
export * from "./component/alert-dialog"
export * from "./component/aspect-ratio"
export * from "./component/avatar"
export * from "./component/badge"
export * from "./component/breadcrumb"
export * from "./component/button"
export * from "./component/button-group"
export * from "./component/calendar"
export * from "./component/card"
export * from "./component/carousel"
export * from "./component/chart"
export * from "./component/checkbox"
export * from "./component/collapsible"
export * from "./component/combobox"
export * from "./component/command"
export * from "./component/context-menu"
export * from "./component/dialog"
export * from "./component/direction"
export * from "./component/drawer"
export * from "./component/dropdown-menu"
export * from "./component/empty"
export * from "./component/field"
export * from "./component/form"
export * from "./component/hover-card"
export * from "./component/input"
export * from "./component/input-group"
export * from "./component/input-otp"
export * from "./component/item"
export * from "./component/kbd"
export * from "./component/label"
export * from "./component/menubar"
export * from "./component/native-select"
export * from "./component/navigation-menu"
export * from "./component/pagination"
export * from "./component/popover"
export * from "./component/progress"
export * from "./component/radio-group"
export * from "./component/resizable"
export * from "./component/scroll-area"
export * from "./component/select"
export * from "./component/separator"
export * from "./component/sheet"
export * from "./component/sidebar"
export * from "./component/skeleton"
export * from "./component/slider"
export * from "./component/sonner"
export * from "./component/spinner"
export * from "./component/switch"
export * from "./component/table"
export * from "./component/tabs"
export * from "./component/textarea"
export * from "./component/theme-provider"
export * from "./component/toast"
export * from "./component/toggle"
export * from "./component/toggle-group"
export * from "./component/tooltip"

export * from "./domain/allocation"
export * from "./domain/invariant"
export * from "./domain/reconciliation"
export * from "./domain/settlement"
export * from "./domain/governed-domain-mappings"

export * from "./policy"

export * from "./registry"
