import type { RepoGuardCoverageDefinition } from "../coverage/repo-guard-coverage.js"

export const repoGuardCoverageCatalog = [
  {
    id: "FOUND-FILESYSTEM",
    title: "Filesystem governance",
    area: "foundation",
    owner: "governance-toolchain",
    baselineStatus: "implemented",
    enforcement: "blocking",
    checkKeys: ["filesystem-governance"],
    evidence: ["scripts/governance/check-filesystem-governance.ts"],
    notes: "Existing governance surface aggregated by repo guard.",
  },
  {
    id: "FOUND-GENERATED-GOVERNANCE",
    title: "Generated artifact governance",
    area: "foundation",
    owner: "governance-toolchain",
    baselineStatus: "implemented",
    enforcement: "blocking",
    checkKeys: ["generated-artifact-governance"],
    evidence: ["scripts/governance/check-generated-artifact-governance.ts"],
    notes: "Existing governance surface aggregated by repo guard.",
  },
  {
    id: "FOUND-STORAGE",
    title: "Storage governance",
    area: "foundation",
    owner: "governance-toolchain",
    baselineStatus: "implemented",
    enforcement: "blocking",
    checkKeys: ["storage-governance"],
    evidence: ["scripts/governance/check-storage-governance.ts"],
    notes: "Existing governance surface aggregated by repo guard.",
  },
  {
    id: "FOUND-NAMING",
    title: "Naming convention",
    area: "foundation",
    owner: "governance-toolchain",
    baselineStatus: "implemented",
    enforcement: "blocking",
    checkKeys: ["naming-convention"],
    evidence: ["scripts/governance/check-naming-convention.ts"],
    notes: "Existing governance surface aggregated by repo guard.",
  },
  {
    id: "FOUND-DOC-GOVERNANCE",
    title: "Documentation governance",
    area: "foundation",
    owner: "docs-policy",
    baselineStatus: "implemented",
    enforcement: "blocking",
    checkKeys: ["documentation-governance"],
    evidence: ["scripts/governance/check-doc-governance.ts"],
    notes: "Existing governance surface aggregated by repo guard.",
  },
  {
    id: "FOUND-WORKSPACE-TOPOLOGY",
    title: "Workspace and package topology",
    area: "foundation",
    owner: "governance-toolchain",
    baselineStatus: "implemented",
    enforcement: "blocking",
    checkKeys: ["workspace-topology"],
    evidence: ["scripts/config/check-afenda-config.ts"],
    notes: "Existing workspace topology governance aggregated by repo guard.",
  },
  {
    id: "FOUND-FILE-SURVIVAL",
    title: "File survival and reviewed survival",
    area: "foundation",
    owner: "governance-toolchain",
    baselineStatus: "implemented",
    enforcement: "blocking",
    checkKeys: ["file-survival"],
    evidence: ["scripts/lib/file-survival-governance.ts"],
    notes: "Existing file survival governance aggregated by repo guard.",
  },
  {
    id: "FOUND-DIRTY-FILE-SCAN",
    title: "Dirty file scan",
    area: "foundation",
    owner: "governance-toolchain",
    baselineStatus: "implemented",
    enforcement: "warned",
    checkKeys: ["dirty-file-scan"],
    evidence: ["scripts/lib/repo-guard.ts"],
    notes: "Native repo-guard hygiene scan.",
  },
  {
    id: "FOUND-WORKTREE-LEGITIMACY",
    title: "Working tree legitimacy",
    area: "foundation",
    owner: "governance-toolchain",
    baselineStatus: "implemented",
    enforcement: "warned",
    checkKeys: ["working-tree-legitimacy"],
    evidence: ["scripts/lib/repo-guard.ts"],
    notes: "Native repo-guard worktree trust check.",
  },
  {
    id: "RG-STRUCT-001",
    title: "Placement and ownership",
    area: "guardrail",
    owner: "governance-toolchain",
    baselineStatus: "partial",
    enforcement: "warned",
    checkKeys: ["placement-ownership"],
    evidence: ["scripts/lib/placement-ownership-guard.ts"],
    notes:
      "Implemented as a first cut; broader repo-wide ownership families still need follow-through.",
  },
  {
    id: "RG-TRUTH-002",
    title: "Generated artifact authenticity",
    area: "guardrail",
    owner: "governance-toolchain",
    baselineStatus: "partial",
    enforcement: "warned",
    checkKeys: ["generated-artifact-authenticity"],
    evidence: ["scripts/lib/generated-artifact-authenticity-guard.ts"],
    notes:
      "Implemented as a first cut; wider provenance coverage still needs follow-through.",
  },
  {
    id: "RG-STRUCT-003",
    title: "Boundary and import regression",
    area: "guardrail",
    owner: "governance-toolchain",
    baselineStatus: "partial",
    enforcement: "warned",
    checkKeys: ["boundary-import-regression"],
    evidence: ["scripts/lib/boundary-import-guard.ts"],
    notes:
      "Implemented as a first cut; package export enforcement is active, but full public-surface policy is still incomplete.",
  },
  {
    id: "RG-STRUCT-004",
    title: "API ownership topology",
    area: "guardrail",
    owner: "governance-toolchain",
    baselineStatus: "partial",
    enforcement: "warned",
    checkKeys: ["api-ownership-topology"],
    evidence: ["scripts/lib/api-ownership-topology-guard.ts"],
    notes:
      "Implemented as a first cut; governed API roots now reject generic top-level function buckets, but wider API topology normalization is still incomplete.",
  },
  {
    id: "RG-TRUTH-004",
    title: "Source and evidence mismatch",
    area: "guardrail",
    owner: "governance-toolchain",
    baselineStatus: "partial",
    enforcement: "warned",
    checkKeys: ["source-evidence-mismatch"],
    evidence: ["scripts/lib/source-evidence-mismatch-guard.ts"],
    notes:
      "Implemented as a first cut; source-to-evidence coverage remains intentionally narrow and high-confidence.",
  },
  {
    id: "RG-HYGIENE-005",
    title: "Duplicate and overlap hygiene",
    area: "guardrail",
    owner: "governance-toolchain",
    baselineStatus: "partial",
    enforcement: "advisory",
    checkKeys: ["duplicate-overlap"],
    evidence: ["scripts/lib/duplicate-overlap-guard.ts"],
    notes:
      "Implemented as a first cut; semantic overlap detection still needs follow-through.",
  },
  {
    id: "RG-ADVISORY-006",
    title: "Advanced document control",
    area: "guardrail",
    owner: "docs-policy",
    baselineStatus: "partial",
    enforcement: "advisory",
    checkKeys: ["stronger-document-control"],
    evidence: ["scripts/lib/stronger-document-control-guard.ts"],
    notes:
      "Implemented as a first cut; deeper doctrine-network validation still needs follow-through.",
  },
] as const satisfies readonly RepoGuardCoverageDefinition[]
