/// <reference types="node" />

import { existsSync } from "fs"
import fs from "fs/promises"
import path from "path"
import prettier from "prettier"
import type { AfendaConfig, ReadmeTargetDefinition } from "./afenda-config.js"
import { loadAfendaConfig, workspaceRoot } from "./afenda-config.js"

interface DocMetadata {
  title?: string
  description?: string
  category?: string
  status?: string
  owner?: string
  truthStatus?: string
  docClass?: string
  relatedDomain?: string
  supersededBy?: string
  order?: number
  hidden?: boolean
}

type FrontMatterData = DocMetadata
type FileOverride = DocMetadata

interface DirectoryOverride {
  title: string
  description: string
  order: number
}

interface DocEntry {
  fileName: string
  absolutePath: string
  relativeToDocs: string
  title: string
  description: string
  category?: string
  status?: string
  owner?: string
  truthStatus?: string
  docClass?: string
  relatedDomain?: string
  supersededBy?: string
  order: number
  hidden: boolean
}

interface DirectoryEntry {
  absolutePath: string
  relativeToDocs: string
  title: string
  description: string
  order: number
}

interface CollectionTaskGuide {
  task: string
  startPath: string
  why: string
}

interface ScriptOverride {
  title?: string
  description?: string
  order?: number
  runCommand?: string
  hidden?: boolean
}

interface ScriptEntry {
  /** Workspace-relative path under `scripts/` (e.g. `check-afenda-config.ts` or `ci/lint-staged.ts`). */
  fileName: string
  absolutePath: string
  title: string
  description: string
  order: number
  runCommand?: string
  hidden: boolean
}

interface ResolvedReadmeTarget {
  absolutePath: string
  relativePath: string
  mode: ReadmeTargetDefinition["mode"]
  title?: string
  description?: string
  includeChildDirectories?: boolean
}

interface ParsedDoc {
  body: string
  frontMatter: FrontMatterData
}

type FrontMatterMode = "strict" | "compat"

interface ParseDocOptions {
  frontMatterMode?: FrontMatterMode
}

interface NarrativeBlock {
  lines: string[]
  heading?: string
  blockIndex: number
  isNearTop: boolean
}

interface GenericChildDirectorySection {
  directoryName: string
  relativePath: string
  title: string
  entries: DocEntry[]
}

interface SummaryCandidate {
  text: string
  score: number
  reason:
    | "opening-paragraph"
    | "how-we-use"
    | "map-to"
    | "red-flags"
    | "section-intro"
    | "generic-block"
}

interface ScriptInsight {
  failureImpact: string
  primaryOutput: string
}

const FRONT_MATTER_KEYS = new Set<keyof DocMetadata>([
  "title",
  "description",
  "category",
  "status",
  "owner",
  "truthStatus",
  "docClass",
  "relatedDomain",
  "supersededBy",
  "order",
  "hidden",
])

const TEXT_FRONT_MATTER_KEYS = new Set<keyof DocMetadata>([
  "title",
  "description",
  "category",
  "status",
  "owner",
  "truthStatus",
  "docClass",
  "relatedDomain",
  "supersededBy",
])

const DOC_TRUTH_STATUS_VALUES = new Set([
  "canonical",
  "supporting",
  "historical",
])

const DOC_CLASS_VALUES = new Set([
  "canonical-doc",
  "supporting-doc",
  "historical-archive",
  "reviewed-exception",
  "delete",
])

const COMPAT_FRONT_MATTER_ALIASES: Partial<
  Record<string, keyof FrontMatterData>
> = {
  name: "title",
}

const TITLE_EXCEPTIONS: Record<string, string> = {
  adr: "ADR",
  ai: "AI",
  api: "API",
  atc: "ATC",
  ci: "CI",
  erp: "ERP",
  i18n: "i18n",
  md: "MD",
  oauth: "OAuth",
  pbac: "PBAC",
  rbac: "RBAC",
  readme: "README",
  sdk: "SDK",
  ui: "UI",
  ux: "UX",
}

const MAX_DESCRIPTION_LENGTH = 170
const MIN_PREFERRED_DESCRIPTION_LENGTH = 90
const DEPENDENCY_CATEGORY_SET = new Set<string>([
  "tooling-platform",
  "web-client-adopted",
  "web-client-installed-not-implemented",
  "web-client-planned",
  "backend-planned",
  "optional",
])

const GENERATED_HEADER = [
  "<!-- This file is auto-generated by `pnpm run script:generate-docs-readme`. -->",
  "<!-- Do not edit this file directly; update the generator or source doc metadata instead. -->",
].join("\n")

const ROOT_FILE_OVERRIDES: Record<string, FileOverride> = {
  "ARCHITECTURE.md": {
    title: "Architecture",
    description:
      "Monorepo + ERP systems view, governed UI layer, semantic adapter flow, and adding new modules.",
    order: 10,
  },
  "API.md": {
    title: "API reference",
    description:
      "REST contract: `/api/tenants/{tenant}/...`, errors, and tenant-scoped routes.",
    order: 20,
  },
  "DOCUMENTATION_SCOPE.md": {
    title: "Documentation scope",
    description:
      "Normative vs optional docs; what blocks implementation and what does not.",
    order: 30,
  },
  "PROJECT_STRUCTURE.md": {
    title: "Project structure",
    description:
      "`apps/web` layout, routes, features, and migration toward `features/*`.",
    order: 40,
  },
  "DESIGN_SYSTEM.md": {
    title: "Design system",
    description: "Tokens, layout, motion, typography, and accessibility rules.",
    order: 50,
  },
  "BRAND_GUIDELINES.md": {
    title: "Brand guidelines",
    description:
      "Logo, palette, gradient rules, and Afenda visual identity guidance.",
    order: 60,
  },
  "COMPONENTS_AND_STYLING.md": {
    title: "Components and styling",
    description:
      "React component patterns, colocation rules, and UI implementation guidance.",
    order: 70,
  },
  "AUTHENTICATION.md": {
    title: "Authentication",
    description:
      "Vite SPA + backend auth flow, sessions, guards, and Auth0 integration notes.",
    order: 90,
  },
  "ROLES_AND_PERMISSIONS.md": {
    title: "Roles and permissions",
    description: "RBAC roles, PBAC permission keys, and API vs UI enforcement.",
    order: 100,
  },
  "STATE_MANAGEMENT.md": {
    title: "State management",
    description:
      "Local state, Zustand, TanStack Query, forms, and Context boundaries.",
    order: 110,
  },
  "PERFORMANCE.md": {
    title: "Performance",
    description:
      "Bundle, list, memoization, and loading-state guidance for the web app.",
    order: 120,
  },
  "VITE_ENTERPRISE_WORKSPACE.md": {
    title: "Vite enterprise practices (workspace)",
    description:
      "Vite 8 + Rolldown quality baseline, apps/web wiring, DevTools/Vitest guards, and review checklist.",
    order: 125,
  },
  "PROJECT_CONFIGURATION.md": {
    title: "Project configuration",
    description:
      "ESLint, Prettier, TypeScript, Turborepo, and repo tooling conventions.",
    order: 130,
  },
  "REPO_ARTIFACT_POLICY.md": {
    title: "Repository artifact policy",
    description:
      "Where build outputs, `.artifacts/` reports, caches, and temp files belong; root anti-patterns.",
    order: 132,
  },
  "TESTING.md": {
    title: "Testing",
    description: "Vitest + React Testing Library guidance for `apps/web`.",
    order: 140,
  },
  "INTEGRATIONS.md": {
    title: "Integrations",
    description: "Third-party APIs, OAuth flows, webhooks, and sync patterns.",
    order: 150,
  },
  "DEPLOYMENT.md": {
    title: "Deployment",
    description:
      "Vercel static deployment, environment variables, and SPA rewrites.",
    order: 160,
  },
  "GLOSSARY.md": {
    title: "Glossary",
    description: "ERP and platform vocabulary used across the repository.",
    order: 170,
  },
  "OPERATING_MAP.md": {
    title: "Operating map",
    description:
      "Generated navigation map for canonical docs, generated surfaces, CI-blocking areas, evidence paths, and contributor starting points.",
    order: 5,
  },
}

const ROOT_COLLECTION_OVERRIDES: Record<string, DirectoryOverride> = {
  architecture: {
    title: "Architecture records",
    description:
      "Architecture ADRs and ATCs grouped under docs/architecture for narrative decisions and enforceable contracts.",
    order: 11,
  },
  governance: {
    title: "Governance",
    description:
      "Repo-local governance doctrine, glossary, generated register, and operating model for checks, evidence, and CI gates.",
    order: 12,
  },
  dependencies: {
    title: "Dependency guides",
    description:
      "Per-package and infrastructure guides for tooling, UI stack, and planned backend integrations.",
    order: 10,
  },
  workspace: {
    title: "Workspace",
    description:
      "Canonical repo-wide operating docs for structure, tooling, architecture, auth, deployment, and platform policy.",
    order: 9,
  },
  "architecture/adr": {
    title: "ADR records",
    description:
      "Narrative architecture decision records that explain what changed, why it changed, and the expected consequences.",
    order: 10,
  },
  "architecture/atc": {
    title: "ATC contracts",
    description:
      "Executable architecture truth contracts for rules that are meant to be enforced, evidenced, and CI-routed.",
    order: 20,
  },
  "architecture/governance": {
    title: "Governance",
    description:
      "Governance doctrine, glossary, and generated register for the repo-local governance spine.",
    order: 30,
  },
  "architecture/scaffolds": {
    title: "Scaffolds and templates",
    description:
      "Reference templates, blueprints, and implementation packs that support canonical workspace policy.",
    order: 40,
  },
  marketing: {
    title: "Marketing",
    description:
      "Flagship marketing briefs and Cursor prompts — e.g. About Company editorial/design override.",
    order: 15,
  },
  scaffolds: {
    title: "Scaffolds and templates",
    description:
      "Supporting implementation packs, templates, and release checklists that sit under canonical repo policy docs.",
    order: 20,
  },
}

const SCRIPT_FILE_OVERRIDES: Record<string, ScriptOverride> = {
  "afenda-config.ts": {
    hidden: true,
  },
  "check-afenda-config.ts": {
    title: "Check Afenda config",
    description:
      "Validates the Afenda workspace manifest, path drift, package manager alignment, and internal package scope usage.",
    order: 5,
    runCommand: "pnpm run script:check-afenda-config",
  },
  "check-architecture-contracts.ts": {
    title: "Check architecture contracts",
    description:
      "Validates ATC files, ADR-to-ATC linkage, and the minimum enforceable contract fields for architecture contracts.",
    order: 6,
    runCommand: "pnpm run script:check-architecture-contracts",
  },
  "check-doc-governance.ts": {
    title: "Check documentation governance",
    description:
      "Checks governance doctrine files, glossary terms, and the ADR/ATC template contract expected by the repo-local governance spine.",
    order: 7,
    runCommand: "pnpm run script:check-doc-governance",
  },
  "check-governance-bindings.ts": {
    title: "Check governance bindings",
    description:
      "Verifies governance registry links resolve to real docs, configs, scripts, and package.json commands.",
    order: 8,
    runCommand: "pnpm run script:check-governance-bindings",
  },
  "check-governance-registry.ts": {
    title: "Check governance registry",
    description:
      "Validates governance ids, lifecycle semantics, maturity rules, tiers, and evidence-path declarations in afenda.config.",
    order: 9,
    runCommand: "pnpm run script:check-governance-registry",
  },
  "check-governance-waivers.ts": {
    title: "Check governance waivers",
    description:
      "Validates waiver ownership, expiry, target ids, and emits the waiver evidence report under .artifacts.",
    order: 10,
    runCommand: "pnpm run script:check-governance-waivers",
  },
  "generate-docs-readme.ts": {
    title: "Generate docs README",
    description:
      "Generates stable `README.md` indexes for `docs/`, `scripts/`, and other readmeTargets configured in `afenda.config.json`.",
    order: 11,
    runCommand: "pnpm run script:generate-docs-readme",
  },
  "generate-governance-register.ts": {
    title: "Generate governance register",
    description:
      "Builds the generated governance register doc and snapshot from afenda.config and the latest aggregate governance evidence.",
    order: 12,
    runCommand: "pnpm run script:generate-governance-register",
  },
  "generate-governance-report.ts": {
    title: "Generate governance report",
    description:
      "Aggregates domain evidence and waiver evidence into repo-level governance core and summary reports.",
    order: 13,
    runCommand: "pnpm run script:generate-governance-report",
  },
  "generate-file-survival-report.ts": {
    title: "Generate file survival report",
    description:
      "Generates report-first file-survival governance audits for configured rollout scopes under `.artifacts/reports/file-survival/`.",
    order: 14,
    runCommand: "pnpm run script:generate-file-survival-report",
  },
  "inspect-node-runtime.ts": {
    title: "Inspect node runtime",
    order: 20,
    runCommand: "pnpm run script:inspect-node-runtime",
  },
  "run-governance-checks.ts": {
    title: "Run governance checks",
    description:
      "Executes the registered governance domain checks, emits per-domain evidence, and applies block vs warn behavior by domain tier.",
    order: 15,
    runCommand: "pnpm run script:run-governance-checks",
  },
}

const DEPENDENCY_FILE_OVERRIDES: Record<string, FileOverride> = {
  "pnpm.md": {
    title: "pnpm",
    description:
      "Workspaces, filters, lockfile policy, and package-manager expectations.",
    category: "tooling-platform",
    order: 10,
  },
  "prettier.md": {
    title: "Prettier",
    description:
      "Formatting, `prettier.config.js`, and lint-staged integration.",
    category: "tooling-platform",
    order: 20,
  },
  "typescript.md": {
    title: "TypeScript",
    description:
      "Shared `tsconfig`, strictness, aliases, and workspace presets.",
    category: "tooling-platform",
    order: 30,
  },
  "eslint.md": {
    title: "ESLint",
    description:
      "Flat config, React rules, a11y checks, and Prettier integration.",
    category: "tooling-platform",
    order: 40,
  },
  "turborepo.md": {
    title: "Turborepo",
    description: "`turbo.json`, task filters, pipelines, and cache usage.",
    category: "tooling-platform",
    order: 50,
  },
  "vercel.md": {
    title: "Vercel",
    description:
      "Static deployment target and pointer to the broader deployment checklist.",
    category: "tooling-platform",
    order: 60,
  },
  "vite.md": {
    title: "Vite",
    description: "Dev server, build, environment variables, and proxy setup.",
    category: "tooling-platform",
    order: 70,
  },
  "vitest.md": {
    title: "Vitest",
    description:
      "Test runner guidance and pointer to the testing strategy docs.",
    category: "tooling-platform",
    order: 80,
  },
  "react.md": {
    title: "React",
    description: "React 19, Router usage, and core UI patterns for `apps/web`.",
    order: 10,
  },
  "tanstack-query.md": {
    title: "TanStack Query",
    description: "Server state, API calls, caching, and invalidation patterns.",
    order: 20,
  },
  "zod.md": {
    title: "Zod",
    description: "Runtime validation, schema conventions, and type inference.",
    order: 30,
  },
  "zustand.md": {
    title: "Zustand",
    description: "Client-only UI state and persistence boundaries.",
    order: 40,
  },
  "react-hook-form-zod.md": {
    title: "React Hook Form + Zod",
    description: "Forms, resolvers, and schema-backed input handling.",
    order: 50,
  },
  "date-fns.md": {
    title: "date-fns",
    description:
      "Date parsing, formatting, locale handling, and timezone helpers.",
    order: 60,
  },
  "tailwind-v4.md": {
    title: "Tailwind CSS v4",
    description: "Utility CSS setup and Vite integration when adopted.",
    order: 10,
  },
  "shadcn-ui.md": {
    title: "shadcn/ui",
    description:
      "Radix-based copy-in components, `components.json`, and theming.",
    order: 20,
  },
  "storybook.md": {
    title: "Storybook",
    description: "Component sandbox and documentation workflow.",
    order: 30,
  },
  "i18n.md": {
    title: "i18n",
    description:
      "Internationalization stack and localization rollout guidance.",
    order: 40,
  },
  "tiptap.md": {
    title: "Tiptap",
    description: "Rich-text editor stack based on ProseMirror.",
    order: 50,
  },
  "xyflow.md": {
    title: "XYFlow",
    description: "Diagramming and node-based UI with `@xyflow/react`.",
    order: 60,
  },
  "wcag-contrast.md": {
    title: "wcag-contrast",
    description:
      "Automated token and contrast checks for accessibility workflows.",
    order: 70,
  },
  "neon.md": {
    title: "Neon",
    description: "Hosted Postgres guidance and `DATABASE_URL` conventions.",
    order: 10,
  },
  "cloudflare-r2.md": {
    title: "Cloudflare R2",
    description:
      "S3-compatible object storage guidance for file-backed workflows.",
    order: 30,
  },
  "fastify.md": {
    title: "Fastify",
    description: "HTTP API implementation guidance for future `apps/api` work.",
    order: 40,
  },
  "pino.md": {
    title: "Pino",
    description:
      "Structured logging patterns for server-side packages and scripts.",
    order: 50,
  },
  "octokit.md": {
    title: "Octokit",
    description: "GitHub API integration guidance for server-side use cases.",
    order: 60,
  },
  "msw.md": {
    title: "MSW",
    description:
      "API mocks in tests and Storybook when the team standardizes them.",
    order: 10,
  },
  "authjs-auth0.md": {
    title: "Auth.js / Auth0",
    description:
      "Authentication-library notes and pointers back to the auth architecture docs.",
    order: 20,
  },
  "vercel-serverless-edge.md": {
    title: "Vercel Serverless / Edge",
    description: "Guidance for in-repo functions if the SPA later gains them.",
    order: 30,
  },
  "sentry-opentelemetry.md": {
    title: "Sentry / OpenTelemetry",
    description:
      "Error monitoring and tracing once observability is standardized.",
    order: 40,
  },
}

const DEPENDENCY_CATEGORY_LABELS: Record<string, string> = {
  "tooling-platform": "Tooling and platform",
  "web-client-adopted": "Web client (adopted)",
  "web-client-installed-not-implemented":
    "Web client (installed, not implemented)",
  "web-client-planned": "Web client (planned)",
  "backend-planned": "Backend, data, and integrations (planned)",
  optional: "Optional / when you standardize",
}

const DEPENDENCY_CATEGORY_ORDER = [
  "tooling-platform",
  "web-client-adopted",
  "web-client-installed-not-implemented",
  "web-client-planned",
  "backend-planned",
  "optional",
] as const

async function main() {
  const afendaConfig = await loadAfendaConfig()
  const docsRoot = path.join(workspaceRoot, "docs")

  assertDependencyCategoryConfiguration()

  await writeIfChanged(
    path.join(docsRoot, "OPERATING_MAP.md"),
    await renderOperatingMap(docsRoot, workspaceRoot, afendaConfig)
  )

  const targets = await resolveReadmeTargets(
    workspaceRoot,
    afendaConfig.readmeTargets
  )

  for (const target of targets) {
    if (target.mode === "docs-root") {
      await writeIfChanged(
        path.join(target.absolutePath, "README.md"),
        await renderRootReadme(target.absolutePath, afendaConfig)
      )
      continue
    }

    if (target.mode === "docs-collections") {
      const docsRoot = path.join(workspaceRoot, "docs")
      const relativeToDocs = toPosixPath(
        path.relative(docsRoot, target.absolutePath)
      )

      if (relativeToDocs === "dependencies") {
        await writeIfChanged(
          path.join(target.absolutePath, "README.md"),
          await renderDependenciesReadme(target.absolutePath, docsRoot)
        )
        continue
      }

      await writeIfChanged(
        path.join(target.absolutePath, "README.md"),
        await renderGenericReadme(target.absolutePath, docsRoot)
      )
      continue
    }

    if (target.mode === "generic-formal-directory") {
      await writeIfChanged(
        path.join(target.absolutePath, "README.md"),
        await renderFormalDirectoryReadme(target, workspaceRoot)
      )
      continue
    }

    await writeIfChanged(
      path.join(target.absolutePath, "README.md"),
      await renderScriptsReadme(
        target.absolutePath,
        workspaceRoot,
        afendaConfig
      )
    )
  }
}

async function resolveReadmeTargets(
  workspaceRoot: string,
  readmeTargets: ReadmeTargetDefinition[]
): Promise<ResolvedReadmeTarget[]> {
  const resolvedTargets: ResolvedReadmeTarget[] = []

  for (const target of readmeTargets) {
    const absolutePath = path.join(workspaceRoot, target.path)

    if (target.mode === "docs-collections") {
      const collectionDirectories = await discoverDirectoriesWithDocs(
        absolutePath,
        false
      )

      resolvedTargets.push(
        ...collectionDirectories.map((directory) => ({
          absolutePath: directory,
          relativePath: toPosixPath(path.relative(workspaceRoot, directory)),
          mode: target.mode,
          title: target.title,
          description: target.description,
        }))
      )
      continue
    }

    resolvedTargets.push({
      absolutePath,
      relativePath: toPosixPath(path.relative(workspaceRoot, absolutePath)),
      mode: target.mode,
      title: target.title,
      description: target.description,
      includeChildDirectories: target.includeChildDirectories,
    })
  }

  return resolvedTargets.sort((left, right) =>
    left.relativePath.localeCompare(right.relativePath)
  )
}

async function discoverDirectoriesWithDocs(
  rootDirectory: string,
  includeRoot = true
) {
  const directories = new Set<string>(includeRoot ? [rootDirectory] : [])

  async function walk(directory: string) {
    const children = await fs.readdir(directory, { withFileTypes: true })

    for (const child of children) {
      if (!child.isDirectory()) {
        continue
      }

      const childDirectory = path.join(directory, child.name)
      const childFiles = await fs.readdir(childDirectory, {
        withFileTypes: true,
      })
      const hasMarkdownDocs = childFiles.some(
        (entry) =>
          entry.isFile() &&
          entry.name.endsWith(".md") &&
          entry.name !== "README.md"
      )
      const hasReadme = childFiles.some(
        (entry) => entry.isFile() && entry.name === "README.md"
      )

      if (hasMarkdownDocs || hasReadme) {
        directories.add(childDirectory)
      }

      await walk(childDirectory)
    }
  }

  await walk(rootDirectory)

  return Array.from(directories).sort((left, right) =>
    left.localeCompare(right)
  )
}

async function renderRootReadme(
  docsRoot: string,
  afendaConfig: AfendaConfig
): Promise<string> {
  const [fileEntries, directoryEntries] = await Promise.all([
    getDocEntries(docsRoot, docsRoot, ROOT_FILE_OVERRIDES),
    getDirectoryEntries(docsRoot),
  ])

  const coreEntries: DocEntry[] = fileEntries.filter(
    (entry) => isVisibleDocEntry(entry) && entry.category !== "redirect"
  )
  const redirectEntries: DocEntry[] = fileEntries.filter(
    (entry) => isVisibleDocEntry(entry) && entry.category === "redirect"
  )

  assertUniqueOrder(coreEntries, "root docs")
  assertUniqueOrder(directoryEntries, "root doc collections")
  assertRequiredDocMetadata(coreEntries, "root docs")
  assertRequiredDocMetadata(redirectEntries, "root redirects")
  assertUniqueTitles(coreEntries, "root docs")
  assertNonEmptyDescriptions(coreEntries, "root docs")
  assertNonEmptyDescriptions(redirectEntries, "root redirects")

  const startHereGuides: CollectionTaskGuide[] = [
    {
      task: "Understand repo navigation and CI-critical surfaces",
      startPath: "OPERATING_MAP.md",
      why: "Start with the operating map for canonical docs, generated surfaces, evidence paths, and CI routing.",
    },
    {
      task: "Read canonical workspace policy",
      startPath: "workspace/README.md",
      why: "Workspace docs are the repo-wide operating source for structure, auth, deployment, and tooling policy.",
    },
    {
      task: "Review architecture decisions and contracts",
      startPath: "architecture/README.md",
      why: "Architecture docs route you to narrative ADRs and enforceable ATCs without mixing the two.",
    },
    {
      task: "Check dependency adoption posture",
      startPath: "dependencies/README.md",
      why: "Dependency guides separate implemented surfaces from installed-only, planned, optional, and research docs.",
    },
  ]

  const sections = [
    GENERATED_HEADER,
    `# ${afendaConfig.product.name} documentation`,
    "",
    renderGeneratedMetadataNotice({
      sourcePaths: ["scripts/generate-docs-readme.ts", "docs/**/*.md"],
      command: "pnpm run script:generate-docs-readme",
      truthClass: "derived",
    }),
    "",
    `This folder is the generated index for repo-wide guides in the ${afendaConfig.product.name} monorepo (\`${afendaConfig.workspace.packageManager}\` + \`Turborepo\`; web client: \`${afendaConfig.paths.webApp}\` with Vite + React).`,
    "",
    "- AI agents: use [`AGENTS.md`](../AGENTS.md) as the execution index and doc map.",
    "- Humans: start here or from the root [`README.md`](../README.md).",
    `- App-specific docs may also live under \`${afendaConfig.paths.webApp}/docs/\` when that package starts owning local guidance.`,
    "",
    `These guides describe ${afendaConfig.product.name}, Vite, and ERP concerns for this repository. They are distinct from the older Next.js template docs preserved elsewhere in the workspace.`,
    "",
    "## Start here",
    "",
    renderTaskGuideTable(docsRoot, startHereGuides),
  ]

  if (coreEntries.length > 0) {
    sections.push(
      "",
      "## Canonical and generated docs in this folder",
      "",
      renderDocMetadataTable(docsRoot, coreEntries)
    )
  }

  sections.push(
    "",
    "## Documentation collections",
    "",
    renderTable(
      ["Collection", "Description"],
      directoryEntries.map((entry) => [
        formatLink(
          docsRoot,
          path.join(entry.absolutePath, "README.md"),
          entry.title
        ),
        entry.description,
      ])
    )
  )

  if (redirectEntries.length > 0) {
    sections.push(
      "",
      "## Compatibility redirects",
      "",
      renderDocMetadataTable(docsRoot, redirectEntries)
    )
  }

  sections.push(
    "",
    "## If governance CI fails",
    "",
    "- Read [Operating map](./OPERATING_MAP.md) first for the current CI routing path and evidence locations.",
    `- Open ${formatExistingRelativeDocLink(
      docsRoot,
      workspaceRoot,
      [
        "docs/architecture/governance/generated/governance-register.md",
        "docs/governance/generated/governance-register.md",
      ],
      "the governance register"
    )} for current domain status and gate context.`,
    `- Review ${formatExistingRelativeDocLink(
      docsRoot,
      workspaceRoot,
      [
        "docs/architecture/governance/GOVERNANCE_CONSTITUTION.md",
        "docs/governance/GOVERNANCE_CONSTITUTION.md",
      ],
      "the governance constitution"
    )} and [scripts README](../scripts/README.md) before changing checks or evidence semantics.`,
    "- Re-run `pnpm run script:check-governance` locally after fixing the relevant area.",
    "",
    "## Not in this folder yet",
    "",
    "The following topics are mentioned elsewhere in the repo but do not exist as repo-root `docs/*.md` files today:",
    "",
    "| Topic | Suggested location / notes |",
    "| --- | --- |",
    "| OpenAPI / generated SDK | Optional. See [Documentation scope](./workspace/DOCUMENTATION_SCOPE.md); not required to implement from [API reference](./workspace/API.md). |",
    "| Storybook deep-dive | Add `docs/STORYBOOK.md` if the team wants repo-level Storybook process guidance beyond the dependency guide. |",
    "| GitHub Actions / CI deep-dive | Add `docs/CI.md` or a focused `.github/workflows` README if CI behavior needs first-class documentation. |",
    "",
    "## Related",
    "",
    "- [`AGENTS.md`](../AGENTS.md) - AI interaction protocol and documentation map.",
    "- [`README.md`](../README.md) - Repository overview and quick links."
  )

  return withTrailingNewline(sections.join("\n"))
}

async function renderDependenciesReadme(
  directory: string,
  docsRoot: string
): Promise<string> {
  const entries = await getDocEntries(
    directory,
    docsRoot,
    DEPENDENCY_FILE_OVERRIDES
  )
  const visibleEntries: DocEntry[] = entries.filter(isVisibleDocEntry)

  const groupedEntries = new Map<string, DocEntry[]>()

  for (const entry of visibleEntries) {
    if (!entry.category) {
      throw new Error(
        `Missing category for ${entry.relativeToDocs}. Add front matter or a generator override.`
      )
    }

    assertKnownDependencyCategory(entry.category, entry.relativeToDocs)

    const group = groupedEntries.get(entry.category) ?? []
    group.push(entry)
    groupedEntries.set(entry.category, group)
  }

  assertRequiredDocMetadata(visibleEntries, "dependency guides")
  assertUniqueTitles(visibleEntries, "dependency guides")
  assertNonEmptyDescriptions(visibleEntries, "dependency guides")

  for (const category of groupedEntries.keys()) {
    assertUniqueOrder(
      groupedEntries.get(category) ?? [],
      `dependencies category "${category}"`
    )
    assertUniqueTitles(
      groupedEntries.get(category) ?? [],
      `dependencies category "${category}"`
    )
  }

  const sections = [
    GENERATED_HEADER,
    "# Dependency guides",
    "",
    renderGeneratedMetadataNotice({
      sourcePaths: [
        "scripts/generate-docs-readme.ts",
        "docs/dependencies/*.md",
      ],
      command: "pnpm run script:generate-docs-readme",
      truthClass: "derived",
    }),
    "",
    "Docs in `docs/dependencies/` describe npm packages, infrastructure, and stack choices used in `apps/web`, repo tooling, or planned backend and integration work.",
    "",
    "Broader UI conventions live in [Design system](../workspace/DESIGN_SYSTEM.md), and repo tooling expectations live in [Project configuration](../workspace/PROJECT_CONFIGURATION.md).",
    "",
    "**Documentation readiness:** [Documentation scope](../workspace/DOCUMENTATION_SCOPE.md).",
    "",
    "## Guide format",
    "",
    "Long-form guides usually share a common shape: Afenda context, official documentation links, usage guidance, red flags, and related references. When behavior-sensitive details matter, verify them against upstream docs before refreshing a guide.",
    "",
    "## Start here",
    "",
    "- Read implemented guides first. They are the only dependency docs that currently describe live repo behavior.",
    "- Treat `Installed, not implemented` guides as posture only, not as proof of a standardized runtime pattern.",
    "- Treat `Planned`, `Optional`, and `Research` guides as decision support, not as approval to install packages without review.",
    "",
    "## Index",
  ]

  for (const category of DEPENDENCY_CATEGORY_ORDER) {
    const categoryEntries = sortEntries(groupedEntries.get(category) ?? [])

    if (categoryEntries.length === 0) {
      continue
    }

    sections.push(
      "",
      `### ${DEPENDENCY_CATEGORY_LABELS[category]}`,
      "",
      renderTable(
        ["Guide", "Status", "Scope"],
        categoryEntries.map((entry) => [
          formatLink(directory, entry.absolutePath, entry.title),
          entry.status ?? "Unspecified",
          entry.description,
        ])
      )
    )
  }

  sections.push(
    "",
    "## Related documentation",
    "",
    "- [Documentation scope](../workspace/DOCUMENTATION_SCOPE.md) - Normative vs optional docs.",
    "- [API reference](../workspace/API.md) - HTTP contract.",
    "- [Database package](../../packages/_database/README.md) — PostgreSQL, Drizzle, migrations."
  )

  return withTrailingNewline(sections.join("\n"))
}

async function renderGenericReadme(
  directory: string,
  docsRoot: string
): Promise<string> {
  const entries = await getDocEntries(directory, docsRoot)
  const visibleEntries: DocEntry[] = sortEntries(
    entries.filter(isVisibleDocEntry)
  )
  const childCollections = await getDirectChildCollectionEntries(
    directory,
    docsRoot
  )
  const relativeDirectory = toPosixPath(path.relative(docsRoot, directory))
  const override = ROOT_COLLECTION_OVERRIDES[relativeDirectory]
  const title =
    override?.title ??
    toTitleCase(relativeDirectory.split("/").at(-1) ?? "Docs")
  const description =
    override?.description ??
    `This index is generated from markdown files in \`docs/${relativeDirectory}\`.`

  assertRequiredDocMetadata(visibleEntries, `docs/${relativeDirectory}`)
  assertUniqueTitles(visibleEntries, `docs/${relativeDirectory}`)
  assertNonEmptyDescriptions(visibleEntries, `docs/${relativeDirectory}`)

  const sections = [
    GENERATED_HEADER,
    `# ${title}`,
    "",
    renderGeneratedMetadataNotice({
      sourcePaths: [
        "scripts/generate-docs-readme.ts",
        `docs/${relativeDirectory}`,
      ],
      command: "pnpm run script:generate-docs-readme",
      truthClass: "derived",
    }),
    "",
    description,
  ]

  const startHereGuides = getCollectionTaskGuides(relativeDirectory)
  if (startHereGuides.length > 0) {
    sections.push(
      "",
      "## Start here",
      "",
      renderTaskGuideTable(directory, startHereGuides)
    )
  }

  if (childCollections.length > 0) {
    sections.push(
      "",
      "## Subcollections",
      "",
      renderTable(
        ["Collection", "Description"],
        childCollections.map((entry) => [
          formatLink(
            directory,
            path.join(entry.absolutePath, "README.md"),
            entry.title
          ),
          entry.description,
        ])
      )
    )
  }

  if (visibleEntries.length > 0) {
    sections.push(
      "",
      "## Documents",
      "",
      renderDocMetadataTable(directory, visibleEntries)
    )
  }

  const relatedCommands = getCollectionRelatedCommands(relativeDirectory)
  if (relatedCommands.length > 0) {
    sections.push(
      "",
      "## Related commands",
      "",
      ...relatedCommands.map((command) => `- \`${command}\``)
    )
  }

  const ciFailureGuidance = getCollectionCiFailureGuidance(relativeDirectory)
  if (ciFailureGuidance.length > 0) {
    sections.push(
      "",
      "## If this area fails in CI",
      "",
      ...ciFailureGuidance.map((line) => `- ${line}`)
    )
  }

  return withTrailingNewline(sections.join("\n"))
}

async function renderScriptsReadme(
  scriptsDirectory: string,
  workspaceRoot: string,
  afendaConfig: AfendaConfig
): Promise<string> {
  const scriptEntries = await getScriptEntries(scriptsDirectory)

  assertUniqueOrder(scriptEntries, "scripts")
  assertUniqueTitles(scriptEntries, "scripts")
  assertNonEmptyScriptDescriptions(scriptEntries, "scripts")

  const sections = [
    GENERATED_HEADER,
    "# Scripts",
    "",
    renderGeneratedMetadataNotice({
      sourcePaths: [
        "scripts/generate-docs-readme.ts",
        "scripts/*.ts",
        "scripts/afenda.config.json",
      ],
      command: "pnpm run script:generate-docs-readme",
      truthClass: "derived",
    }),
    "",
    `This directory contains small Node/TypeScript CLI utilities and script-local metadata used for repository maintenance and automation in ${afendaConfig.workspace.rootPackageName}.`,
    "",
    `Run scripts from the repository root with \`${afendaConfig.workspace.packageManager}\` so they use the workspace toolchain and \`tsx\` configuration.`,
    "",
    "Layout and contribution rules (flat vs one subdirectory) live in [`RULES.md`](./RULES.md).",
    "",
    "## Start here",
    "",
    "- Governance work: start with `script:check-governance`, then inspect the narrower registry, binding, or waiver scripts only if that aggregate flow fails.",
    "- Docs navigation work: start with `script:generate-docs-readme` because the generated indexes and operating map are derived from this generator.",
    "- Workspace topology drift: start with `script:check-afenda-config` before editing package layout rules.",
    "",
    renderTable(
      ["Script", "Run", "Failure impact", "Primary output", "Purpose"],
      scriptEntries.map((entry) => [
        formatLink(scriptsDirectory, entry.absolutePath, entry.title),
        entry.runCommand ? `\`${entry.runCommand}\`` : "N/A",
        getScriptInsight(entry, afendaConfig).failureImpact,
        getScriptInsight(entry, afendaConfig).primaryOutput,
        entry.description,
      ])
    ),
    "",
    "## If governance CI fails",
    "",
    "- Start with `pnpm run script:check-governance` so registry, bindings, domain checks, evidence generation, and register sync are evaluated in CI order.",
    "- Read [Operating map](../docs/OPERATING_MAP.md) and the generated governance register before changing individual script semantics.",
    "- When a script emits evidence, treat the `.artifacts/reports/governance/**` output as part of the fix, not as optional byproduct.",
    "",
    "## Support files",
    "",
    "| File | Purpose |",
    "| --- | --- |",
    `| [\`afenda.config.json\`](./afenda.config.json) | Verified workspace manifest for ${afendaConfig.product.name} identity, key paths, workspace defaults, and governance bindings. |`,
    "| [`afenda.config.schema.json`](./afenda.config.schema.json) | JSON Schema for the Afenda workspace manifest. |",
    "| [`tsconfig.json`](./tsconfig.json) | Type-check configuration for this directory's Node scripts. |",
    "| [`RULES.md`](./RULES.md) | Authoritative layout, naming, and flat vs one-level-nested folder policy for `scripts/`. |",
    "",
    "## Governed README targets",
    "",
    renderTable(
      ["Path", "Mode", "Notes"],
      afendaConfig.readmeTargets.map((target) => [
        `\`${target.path}\``,
        `\`${target.mode}\``,
        target.description ?? target.title ?? "Config-driven README target.",
      ])
    ),
    "",
    "## Related",
    "",
    `- [Root README](${relativeMarkdownPath(scriptsDirectory, path.join(workspaceRoot, "README.md"))}) - Repository overview and top-level workflows.`,
    `- [Operating map](${relativeMarkdownPath(scriptsDirectory, path.join(workspaceRoot, "docs", "OPERATING_MAP.md"))}) - Canonical docs, generated surfaces, CI routes, and evidence map.`,
    `- [Package manifest](${relativeMarkdownPath(scriptsDirectory, path.join(workspaceRoot, "package.json"))}) - Root scripts and shared dev tooling.`,
  ]

  return withTrailingNewline(sections.join("\n"))
}

async function renderOperatingMap(
  docsRoot: string,
  workspaceRoot: string,
  afendaConfig: AfendaConfig
): Promise<string> {
  const governanceRegisterPath =
    findExistingRelativePath(workspaceRoot, [
      "docs/architecture/governance/generated/governance-register.md",
      afendaConfig.governance.evidence.registerPath,
    ]) ?? afendaConfig.governance.evidence.registerPath
  const governanceSummary = await readJsonIfExists<{
    totalDomains: number
    passedDomains: number
    warnedDomains: number
    blockedDomains: number
    finalVerdict: string
    finalVerdictExplanation: string
    verdictReasons: string[]
    evidenceCompleteCount: number
    activeWaiverCount: number
    expiredWaiverCount: number
  }>(
    path.join(
      workspaceRoot,
      ".artifacts/reports/governance/governance-summary.report.json"
    )
  )

  const sections = [
    "---",
    "owner: governance-toolchain",
    "truthStatus: supporting",
    "docClass: supporting-doc",
    "relatedDomain: operating-map",
    "title: Operating map",
    "description: Generated navigation map for canonical docs, generated surfaces, CI-blocking areas, and evidence paths.",
    "order: 5",
    "---",
    "",
    GENERATED_HEADER,
    "# Operating map",
    "",
    renderGeneratedMetadataNotice({
      sourcePaths: [
        "scripts/generate-docs-readme.ts",
        "scripts/afenda.config.json",
        ".artifacts/reports/governance/governance-summary.report.json",
      ],
      command: "pnpm run script:generate-docs-readme",
      truthClass: "derived",
    }),
    "",
    "This document is the repo-local navigation surface for contributors. It explains what is canonical, what is generated, what blocks CI, and where to start based on the kind of change you are making.",
    "",
    "## Start by task",
    "",
    renderTaskGuideTable(docsRoot, [
      {
        task: "Change repo-wide implementation policy or workspace guidance",
        startPath: "workspace/README.md",
        why: "Workspace docs are the canonical starting point for repo-wide implementation changes.",
      },
      {
        task: "Change architecture decisions or enforceable contracts",
        startPath: "architecture/README.md",
        why: "Architecture docs route you to ADRs for decision history and ATCs for enforceable contracts.",
      },
      {
        task: "Diagnose governance CI failures",
        startPath: (
          findExistingRelativePath(workspaceRoot, [
            "docs/architecture/governance/generated/governance-register.md",
            "docs/governance/generated/governance-register.md",
          ]) ?? "docs/architecture/governance/generated/governance-register.md"
        ).replace(/^docs\//, ""),
        why: "The governance register shows current domain status, evidence paths, and CI behavior in one place.",
      },
      {
        task: "Update generated docs navigation",
        startPath: "../scripts/README.md",
        why: "The docs generator owns the generated README indexes and this operating map.",
      },
    ]),
    "",
    "## Canonical docs first",
    "",
    renderBulletLinks(docsRoot, workspaceRoot, [
      "docs/workspace/README.md",
      "docs/architecture/README.md",
      "docs/architecture/adr/README.md",
      "docs/architecture/atc/README.md",
      "docs/architecture/governance/GOVERNANCE_CONSTITUTION.md",
      "docs/workspace/PROJECT_STRUCTURE.md",
      "docs/workspace/REPO_ARTIFACT_POLICY.md",
    ]),
    "",
    "## Generated and derived surfaces",
    "",
    renderBulletLinks(docsRoot, workspaceRoot, [
      "docs/README.md",
      "docs/OPERATING_MAP.md",
      "docs/dependencies/README.md",
      "docs/architecture/README.md",
      "docs/architecture/governance/generated/governance-register.md",
      "scripts/README.md",
    ]),
    "",
    "## Governance and CI blocking surfaces",
    "",
    renderTable(
      ["Gate", "CI behavior", "Command", "Purpose"],
      afendaConfig.governance.gates.map((gate) => [
        `\`${gate.id}\``,
        `\`${gate.ciBehavior}\``,
        `\`${gate.command}\``,
        gate.description,
      ])
    ),
    "",
    "## Evidence map",
    "",
    renderTable(
      ["Surface", "Path"],
      [
        [
          "Governance evidence root",
          `\`${afendaConfig.governance.evidence.root}\``,
        ],
        [
          "Aggregate governance report",
          `\`${afendaConfig.governance.evidence.aggregateReportPath}\``,
        ],
        [
          "Governance summary report",
          `\`${afendaConfig.governance.evidence.summaryReportPath}\``,
        ],
        ["Governance register", `\`${governanceRegisterPath}\``],
        [
          "Governance register snapshot",
          `\`${afendaConfig.governance.evidence.registerSnapshotPath}\``,
        ],
        [
          "Waiver registry",
          `\`${afendaConfig.governance.waivers.registryPath}\``,
        ],
        [
          "Waiver evidence report",
          `\`${afendaConfig.governance.waivers.reportPath}\``,
        ],
      ]
    ),
  ]

  if (governanceSummary) {
    sections.push(
      "",
      "## Current governance summary",
      "",
      `- Final verdict: \`${governanceSummary.finalVerdict}\``,
      `- Explanation: ${governanceSummary.finalVerdictExplanation}`,
      `- Verdict reasons: ${governanceSummary.verdictReasons.join(", ") || "none"}`,
      `- Domains: ${governanceSummary.totalDomains} total; ${governanceSummary.passedDomains} passed; ${governanceSummary.warnedDomains} warned; ${governanceSummary.blockedDomains} blocked`,
      `- Evidence complete: ${governanceSummary.evidenceCompleteCount} / ${governanceSummary.totalDomains}`,
      `- Active waivers: ${governanceSummary.activeWaiverCount}; expired waivers: ${governanceSummary.expiredWaiverCount}`
    )
  }

  sections.push(
    "",
    "## If governance CI fails",
    "",
    "- Run `pnpm run script:check-governance` from the repo root.",
    "- Open the generated governance register and the relevant evidence report under `.artifacts/reports/governance/`.",
    "- If the failure is architectural, start with `docs/architecture/atc/` before editing code or policy text.",
    "- If the failure is documentation or navigation, regenerate docs with `pnpm run script:generate-docs-readme` after the fix.",
    "",
    "## Related",
    "",
    "- [Docs root](./README.md) - Generated docs index.",
    "- [Scripts README](../scripts/README.md) - Script inventory, failure impact, and primary outputs.",
    "- [Repository README](../README.md) - Top-level overview and workflows."
  )

  return withTrailingNewline(sections.join("\n"))
}

function renderGeneratedMetadataNotice(input: {
  sourcePaths: string[]
  command: string
  truthClass: "derived"
}) {
  return [
    `> Generated from: ${input.sourcePaths
      .map((sourcePath) => `\`${sourcePath}\``)
      .join(", ")}`,
    `> Regenerate with: \`${input.command}\``,
    `> Truth class: \`${input.truthClass}\``,
    "> Do not edit directly.",
  ].join("\n")
}

function renderDocMetadataTable(
  baseDirectory: string,
  entries: readonly DocEntry[]
) {
  return renderTable(
    ["Document", "Priority", "Truth", "Class", "Owner", "Description"],
    entries.map((entry) => [
      formatLink(baseDirectory, entry.absolutePath, entry.title),
      getReadPriority(entry),
      entry.truthStatus ?? "unspecified",
      entry.docClass ?? "unspecified",
      entry.owner ?? "unspecified",
      entry.description,
    ])
  )
}

function getReadPriority(entry: DocEntry) {
  if (entry.docClass === "canonical-doc" || entry.truthStatus === "canonical") {
    return "Read first"
  }

  if (
    entry.docClass === "historical-archive" ||
    entry.truthStatus === "historical"
  ) {
    return "Historical"
  }

  return "Reference"
}

function renderTaskGuideTable(
  baseDirectory: string,
  guides: readonly CollectionTaskGuide[]
) {
  return renderTable(
    ["Task", "Start here", "Why"],
    guides.map((guide) => [
      guide.task,
      formatGuidePath(baseDirectory, guide.startPath),
      guide.why,
    ])
  )
}

function formatGuidePath(baseDirectory: string, startPath: string) {
  const normalized = toPosixPath(startPath)

  if (normalized.startsWith("../")) {
    return `[Open](${normalized})`
  }

  return `[Open](${relativeMarkdownPath(
    baseDirectory,
    path.join(baseDirectory, normalized)
  )})`
}

function getCollectionTaskGuides(
  relativeDirectory: string
): CollectionTaskGuide[] {
  switch (relativeDirectory) {
    case "workspace":
      return [
        {
          task: "Find canonical implementation policy",
          startPath: "PROJECT_STRUCTURE.md",
          why: "Workspace docs hold the durable repo-wide implementation guidance for structure and operating conventions.",
        },
        {
          task: "Change auth, deployment, or toolchain behavior",
          startPath: "PROJECT_CONFIGURATION.md",
          why: "Configuration and workspace docs are the canonical start for shared runtime and tooling changes.",
        },
      ]
    case "architecture":
      return [
        {
          task: "Read decision history",
          startPath: "adr/README.md",
          why: "ADRs explain what was decided, why it was decided, and the expected consequences.",
        },
        {
          task: "Check enforceable contracts",
          startPath: "atc/README.md",
          why: "ATCs describe architecture surfaces that are bound to checks, evidence, and CI behavior.",
        },
        {
          task: "Understand governance doctrine",
          startPath: "governance/README.md",
          why: "Governance docs explain how architecture, evidence, and CI truth are tied together.",
        },
      ]
    case "dependencies":
      return [
        {
          task: "Check what is actually implemented",
          startPath: "README.md",
          why: "Implemented dependency guides are the only ones that should be treated as live repo behavior.",
        },
      ]
    default:
      return []
  }
}

function getCollectionRelatedCommands(relativeDirectory: string) {
  switch (relativeDirectory) {
    case "workspace":
      return [
        "pnpm run script:generate-docs-readme",
        "pnpm run script:check-doc-governance",
      ]
    case "architecture":
      return [
        "pnpm run script:check-architecture-contracts",
        "pnpm run script:check-governance",
      ]
    case "dependencies":
      return ["pnpm run script:generate-docs-readme"]
    default:
      return []
  }
}

function getCollectionCiFailureGuidance(relativeDirectory: string) {
  switch (relativeDirectory) {
    case "architecture":
      return [
        "open `docs/OPERATING_MAP.md` first to see the current CI routing and evidence surfaces",
        "review the ATC or ADR linked to the failing area before editing checks",
        "re-run `pnpm run script:check-architecture-contracts` after the fix",
      ]
    case "workspace":
      return [
        "start with `pnpm run script:check-doc-governance` for docs issues or `pnpm run script:check-afenda-config` for topology issues",
        "regenerate docs with `pnpm run script:generate-docs-readme` after changing any generated index surface",
      ]
    default:
      return []
  }
}

function formatExistingRelativeDocLink(
  fromDirectory: string,
  workspaceRoot: string,
  candidates: string[],
  label: string
) {
  const resolved = findExistingRelativePath(workspaceRoot, candidates)

  if (!resolved) {
    return `\`${label}\``
  }

  return formatLink(fromDirectory, path.join(workspaceRoot, resolved), label)
}

function renderBulletLinks(
  fromDirectory: string,
  workspaceRoot: string,
  relativePaths: string[]
) {
  const lines = relativePaths
    .map((relativePath) =>
      findExistingRelativePath(workspaceRoot, [relativePath])
    )
    .filter((value): value is string => Boolean(value))
    .map((relativePath) => {
      const absolutePath = path.join(workspaceRoot, relativePath)
      const label = relativePath
        .replace(/^docs\//, "")
        .replace(/^scripts\//, "scripts/")

      return `- ${formatLink(fromDirectory, absolutePath, label)}`
    })

  return lines.join("\n")
}

function findExistingRelativePath(
  workspaceRoot: string,
  candidates: readonly string[]
) {
  for (const candidate of candidates) {
    if (existsSync(path.join(workspaceRoot, candidate))) {
      return candidate
    }
  }

  return undefined
}

async function readJsonIfExists<T>(filePath: string): Promise<T | undefined> {
  try {
    return JSON.parse(await fs.readFile(filePath, "utf8")) as T
  } catch (error) {
    const code =
      typeof error === "object" && error && "code" in error
        ? String((error as { code?: string }).code)
        : ""

    if (code === "ENOENT") {
      return undefined
    }

    throw error
  }
}

function getScriptInsight(
  entry: ScriptEntry,
  afendaConfig: AfendaConfig
): ScriptInsight {
  const scriptPath = `scripts/${toPosixPath(entry.fileName)}`

  if (entry.fileName === "generate-governance-report.ts") {
    return {
      failureImpact: "Blocks CI when governance evidence is incomplete",
      primaryOutput:
        `\`${afendaConfig.governance.evidence.aggregateReportPath}\`, ` +
        `\`${afendaConfig.governance.evidence.summaryReportPath}\``,
    }
  }

  if (entry.fileName === "generate-governance-register.ts") {
    const registerPath =
      findExistingRelativePath(workspaceRoot, [
        "docs/architecture/governance/generated/governance-register.md",
        afendaConfig.governance.evidence.registerPath,
      ]) ?? afendaConfig.governance.evidence.registerPath

    return {
      failureImpact: "Blocks CI when the register is out of sync",
      primaryOutput:
        `\`${registerPath}\`, ` +
        `\`${afendaConfig.governance.evidence.registerSnapshotPath}\``,
    }
  }

  if (entry.fileName === "generate-docs-readme.ts") {
    return {
      failureImpact: "Generated docs only",
      primaryOutput:
        "`README.md` indexes under configured targets plus `docs/OPERATING_MAP.md`",
    }
  }

  if (entry.fileName === "check-governance-waivers.ts") {
    return {
      failureImpact: "Blocks CI when waiver policy is invalid",
      primaryOutput: `\`${afendaConfig.governance.waivers.reportPath}\``,
    }
  }

  const gate = afendaConfig.governance.gates.find(
    (candidate) => candidate.scriptPath === scriptPath
  )
  const checkDomain = afendaConfig.governance.domains.find((domain) =>
    domain.checks.some((check) => check.scriptPath === scriptPath)
  )
  const reportDomain = afendaConfig.governance.domains.find(
    (domain) => domain.report.scriptPath === scriptPath
  )

  if (gate) {
    return {
      failureImpact:
        gate.ciBehavior === "block"
          ? `Blocks CI via \`${gate.id}\``
          : `Warns via \`${gate.id}\``,
      primaryOutput: reportDomain
        ? `\`${reportDomain.evidencePath}\``
        : "Validation or orchestration output",
    }
  }

  if (checkDomain) {
    return {
      failureImpact:
        checkDomain.ciBehavior === "block"
          ? `Blocks \`${checkDomain.id}\``
          : `Warns \`${checkDomain.id}\``,
      primaryOutput: `Validation for \`${checkDomain.evidencePath}\``,
    }
  }

  if (reportDomain) {
    return {
      failureImpact:
        reportDomain.ciBehavior === "block"
          ? `Supports blocking evidence for \`${reportDomain.id}\``
          : `Supports warning evidence for \`${reportDomain.id}\``,
      primaryOutput: `\`${reportDomain.evidencePath}\``,
    }
  }

  return {
    failureImpact: "Local utility or support command",
    primaryOutput: "Validation only",
  }
}

async function renderFormalDirectoryReadme(
  target: ResolvedReadmeTarget,
  workspaceRoot: string
): Promise<string> {
  const entries = await getDocEntries(
    target.absolutePath,
    target.absolutePath,
    {},
    {
      frontMatterMode: "compat",
    }
  )
  const visibleEntries: DocEntry[] = sortEntries(
    entries.filter(isVisibleDocEntry)
  )
  const title =
    target.title ??
    toTitleCase(path.basename(target.absolutePath).replace(/[-_]/g, " "))
  const description =
    target.description ??
    `This directory contains formal project documentation and generated index entries for \`${target.relativePath}\`.`

  assertUniqueTitles(visibleEntries, target.relativePath)
  assertNonEmptyDescriptions(visibleEntries, target.relativePath)

  const childSections = target.includeChildDirectories
    ? await getGenericChildDirectorySections(target)
    : []

  const sections = [
    GENERATED_HEADER,
    `# ${title}`,
    "",
    renderGeneratedMetadataNotice({
      sourcePaths: ["scripts/generate-docs-readme.ts", target.relativePath],
      command: "pnpm run script:generate-docs-readme",
      truthClass: "derived",
    }),
    "",
    description,
  ]

  if (visibleEntries.length > 0) {
    sections.push(
      "",
      renderDocMetadataTable(target.absolutePath, visibleEntries)
    )
  }

  for (const childSection of childSections) {
    sections.push(
      "",
      `## ${childSection.title}`,
      "",
      `Markdown docs in \`${childSection.relativePath}\`.`,
      "",
      renderDocMetadataTable(target.absolutePath, childSection.entries)
    )
  }

  sections.push(
    "",
    "## Related",
    "",
    `- [Root README](${relativeMarkdownPath(target.absolutePath, path.join(workspaceRoot, "README.md"))}) - Repository overview and top-level workflows.`,
    `- [Operating map](${relativeMarkdownPath(target.absolutePath, path.join(workspaceRoot, "docs", "OPERATING_MAP.md"))}) - Canonical docs, generated surfaces, CI routes, and evidence map.`,
    `- [Package manifest](${relativeMarkdownPath(target.absolutePath, path.join(workspaceRoot, "package.json"))}) - Root scripts and shared tooling.`
  )

  return withTrailingNewline(sections.join("\n"))
}

async function getGenericChildDirectorySections(
  target: ResolvedReadmeTarget
): Promise<GenericChildDirectorySection[]> {
  const children = await fs.readdir(target.absolutePath, {
    withFileTypes: true,
  })

  const sections = await Promise.all(
    children
      .filter((child) => child.isDirectory())
      .map(async (child) => {
        const childDirectory = path.join(target.absolutePath, child.name)
        const entries = await getDocEntries(
          childDirectory,
          target.absolutePath,
          {},
          {
            frontMatterMode: "compat",
          }
        )
        const visibleEntries = sortEntries(entries.filter(isVisibleDocEntry))

        if (visibleEntries.length === 0) {
          return undefined
        }

        const relativePath = toPosixPath(
          path.relative(target.absolutePath, childDirectory)
        )

        assertUniqueTitles(
          visibleEntries,
          `${target.relativePath}/${relativePath}`
        )
        assertNonEmptyDescriptions(
          visibleEntries,
          `${target.relativePath}/${relativePath}`
        )

        return {
          directoryName: child.name,
          relativePath: toPosixPath(
            path.join(target.relativePath, relativePath)
          ),
          title: toTitleCase(child.name),
          entries: visibleEntries,
        } satisfies GenericChildDirectorySection
      })
  )

  return sections
    .filter((section): section is GenericChildDirectorySection =>
      Boolean(section)
    )
    .sort(
      (left, right) =>
        left.title.localeCompare(right.title) ||
        left.directoryName.localeCompare(right.directoryName)
    )
}

async function getDirectoryEntries(
  docsRoot: string
): Promise<DirectoryEntry[]> {
  const children = await fs.readdir(docsRoot, { withFileTypes: true })

  const directories = await Promise.all(
    children
      .filter((child) => child.isDirectory())
      .map(async (child) => {
        const childDirectory = path.join(docsRoot, child.name)
        const childFiles = await fs.readdir(childDirectory, {
          withFileTypes: true,
        })
        const hasMarkdownDocs = childFiles.some(
          (entry) =>
            entry.isFile() &&
            entry.name.endsWith(".md") &&
            entry.name !== "README.md"
        )
        const hasReadme = childFiles.some(
          (entry) => entry.isFile() && entry.name === "README.md"
        )

        if (!hasMarkdownDocs && !hasReadme) {
          return undefined
        }

        const relativePath = toPosixPath(
          path.relative(docsRoot, childDirectory)
        )
        const override =
          ROOT_COLLECTION_OVERRIDES[relativePath] ??
          ROOT_COLLECTION_OVERRIDES[child.name]

        return {
          absolutePath: childDirectory,
          relativeToDocs: relativePath,
          title: override?.title ?? toTitleCase(child.name),
          description:
            override?.description ??
            `Generated index for docs in \`docs/${relativePath}\`.`,
          order: override?.order ?? 999,
        } satisfies DirectoryEntry
      })
  )

  return directories.filter(Boolean).sort((left, right) => {
    if (!left || !right) {
      return 0
    }

    return left.order - right.order || left.title.localeCompare(right.title)
  }) as DirectoryEntry[]
}

async function getDirectChildCollectionEntries(
  directory: string,
  docsRoot: string
): Promise<DirectoryEntry[]> {
  const children = await fs.readdir(directory, { withFileTypes: true })

  const directories = await Promise.all(
    children
      .filter((child) => child.isDirectory())
      .map(async (child) => {
        const childDirectory = path.join(directory, child.name)
        const childFiles = await fs.readdir(childDirectory, {
          withFileTypes: true,
        })
        const hasMarkdownDocs = childFiles.some(
          (entry) =>
            entry.isFile() &&
            entry.name.endsWith(".md") &&
            entry.name !== "README.md"
        )
        const hasReadme = childFiles.some(
          (entry) => entry.isFile() && entry.name === "README.md"
        )

        if (!hasMarkdownDocs && !hasReadme) {
          return undefined
        }

        const relativePath = toPosixPath(
          path.relative(docsRoot, childDirectory)
        )
        const override =
          ROOT_COLLECTION_OVERRIDES[relativePath] ??
          ROOT_COLLECTION_OVERRIDES[child.name]

        return {
          absolutePath: childDirectory,
          relativeToDocs: relativePath,
          title: override?.title ?? toTitleCase(child.name),
          description:
            override?.description ??
            `Generated index for docs in \`docs/${relativePath}\`.`,
          order: override?.order ?? 999,
        } satisfies DirectoryEntry
      })
  )

  return directories.filter(Boolean).sort((left, right) => {
    if (!left || !right) {
      return 0
    }

    return left.order - right.order || left.title.localeCompare(right.title)
  }) as DirectoryEntry[]
}

async function collectScriptTsFiles(scriptsDirectory: string) {
  const results: Array<{ relativePath: string; absolutePath: string }> = []
  const children = await fs.readdir(scriptsDirectory, { withFileTypes: true })

  for (const child of children) {
    if (child.name.startsWith(".") || child.name === "node_modules") {
      continue
    }

    const childPath = path.join(scriptsDirectory, child.name)

    if (child.isFile() && child.name.endsWith(".ts")) {
      results.push({ relativePath: child.name, absolutePath: childPath })
      continue
    }

    if (!child.isDirectory()) {
      continue
    }

    const subChildren = await fs.readdir(childPath, { withFileTypes: true })

    for (const subChild of subChildren) {
      if (!subChild.isFile() || !subChild.name.endsWith(".ts")) {
        continue
      }

      const relativePath = toPosixPath(path.join(child.name, subChild.name))

      results.push({
        relativePath,
        absolutePath: path.join(childPath, subChild.name),
      })
    }
  }

  return results.sort((left, right) =>
    left.relativePath.localeCompare(right.relativePath)
  )
}

async function getScriptEntries(
  scriptsDirectory: string
): Promise<ScriptEntry[]> {
  const scriptFiles = await collectScriptTsFiles(scriptsDirectory)

  const entries = await Promise.all(
    scriptFiles.map(async ({ relativePath, absolutePath }) => {
      const content = await fs.readFile(absolutePath, "utf8")
      const override = SCRIPT_FILE_OVERRIDES[relativePath]
      const baseTitle = titleFromFileName(path.basename(relativePath))
      const title =
        override?.title ??
        (relativePath.includes("/")
          ? `${toTitleCase(relativePath.split("/")[0] ?? "")} · ${baseTitle}`
          : baseTitle)
      const description =
        override?.description ?? extractScriptDescription(content, title)

      return {
        fileName: relativePath,
        absolutePath,
        title,
        description,
        order: override?.order ?? 999,
        runCommand: override?.runCommand ?? extractScriptRunCommand(content),
        hidden: override?.hidden ?? false,
      } satisfies ScriptEntry
    })
  )

  // Keep internal helpers out of the runnable script index unless they expose an
  // explicit run command. Support files are documented separately below.
  return sortEntries(
    entries.filter((entry) => !entry.hidden && Boolean(entry.runCommand))
  )
}

async function getDocEntries(
  directory: string,
  docsRoot: string,
  overrides: Record<string, FileOverride> = {},
  options: ParseDocOptions = {}
): Promise<DocEntry[]> {
  const children = await fs.readdir(directory, { withFileTypes: true })
  const markdownFiles = children
    .filter(
      (child) =>
        child.isFile() &&
        child.name.endsWith(".md") &&
        child.name !== "README.md"
    )
    .map((child) => child.name)

  const entries = await Promise.all(
    markdownFiles.map(async (fileName) => {
      const absolutePath = path.join(directory, fileName)
      const relativeToDocs = toPosixPath(path.relative(docsRoot, absolutePath))
      const parsedDoc = parseDoc(
        await fs.readFile(absolutePath, "utf8"),
        relativeToDocs,
        options
      )
      const override = overrides[fileName]

      const title =
        override?.title ??
        parsedDoc.frontMatter.title ??
        extractTitle(parsedDoc.body, fileName)
      const description =
        override?.description ??
        parsedDoc.frontMatter.description ??
        extractDescription(parsedDoc.body, title)
      const category = override?.category ?? parsedDoc.frontMatter.category
      const status =
        override?.status ??
        parsedDoc.frontMatter.status ??
        extractStatus(parsedDoc.body)
      const owner = parsedDoc.frontMatter.owner
      const truthStatus = parsedDoc.frontMatter.truthStatus
      const docClass = parsedDoc.frontMatter.docClass
      const relatedDomain = parsedDoc.frontMatter.relatedDomain
      const supersededBy = parsedDoc.frontMatter.supersededBy
      const order = override?.order ?? parsedDoc.frontMatter.order ?? 999
      const hidden = override?.hidden ?? parsedDoc.frontMatter.hidden ?? false

      return {
        fileName,
        absolutePath,
        relativeToDocs,
        title,
        description,
        category,
        status,
        owner,
        truthStatus,
        docClass,
        relatedDomain,
        supersededBy,
        order,
        hidden,
      } satisfies DocEntry
    })
  )

  return sortEntries(entries)
}

function parseDoc(
  rawContent: string,
  relativePath: string,
  options: ParseDocOptions = {}
): ParsedDoc {
  const lines = rawContent.split(/\r?\n/)
  const frontMatterMode = options.frontMatterMode ?? "strict"

  if (lines[0] !== "---") {
    return {
      body: rawContent,
      frontMatter: {},
    }
  }

  let closingIndex = -1

  for (let index = 1; index < lines.length; index += 1) {
    if (lines[index] === "---") {
      closingIndex = index
      break
    }
  }

  if (closingIndex === -1) {
    throw new Error(`Unclosed front matter in ${relativePath}`)
  }

  const frontMatter: FrontMatterData = {}

  for (const line of lines.slice(1, closingIndex)) {
    if (!line.trim()) {
      continue
    }

    const match = line.match(/^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/)

    if (!match) {
      throw new Error(`Invalid front matter line "${line}" in ${relativePath}`)
    }

    const [, rawKey, rawValue] = match
    const aliasKey = COMPAT_FRONT_MATTER_ALIASES[rawKey]
    const key = (aliasKey ?? rawKey) as keyof FrontMatterData

    if (!FRONT_MATTER_KEYS.has(key)) {
      if (frontMatterMode === "compat") {
        continue
      }

      throw new Error(
        `Unknown front matter key "${rawKey}" in ${relativePath}. Allowed keys: ${Array.from(FRONT_MATTER_KEYS).join(", ")}`
      )
    }

    const value = parseFrontMatterValue(rawValue.trim())

    if (key === "order" && typeof value !== "number") {
      throw new Error(
        `Front matter "order" must be a number in ${relativePath}`
      )
    }

    if (key === "hidden" && typeof value !== "boolean") {
      throw new Error(
        `Front matter "hidden" must be true or false in ${relativePath}`
      )
    }

    if (TEXT_FRONT_MATTER_KEYS.has(key)) {
      if (typeof value !== "string") {
        throw new Error(
          `Front matter "${rawKey}" must be a string in ${relativePath}`
        )
      }

      if (value.trim().length === 0) {
        throw new Error(
          `Front matter "${rawKey}" cannot be empty in ${relativePath}`
        )
      }
    }

    if (
      key === "truthStatus" &&
      typeof value === "string" &&
      !DOC_TRUTH_STATUS_VALUES.has(value)
    ) {
      throw new Error(
        `Front matter "truthStatus" must be one of ${Array.from(DOC_TRUTH_STATUS_VALUES).join(", ")} in ${relativePath}`
      )
    }

    if (
      key === "docClass" &&
      typeof value === "string" &&
      !DOC_CLASS_VALUES.has(value)
    ) {
      throw new Error(
        `Front matter "docClass" must be one of ${Array.from(DOC_CLASS_VALUES).join(", ")} in ${relativePath}`
      )
    }

    frontMatter[key] = value as never
  }

  return {
    frontMatter,
    body: lines.slice(closingIndex + 1).join("\n"),
  }
}

function parseFrontMatterValue(rawValue: string) {
  const quotedMatch = rawValue.match(/^['"](.*)['"]$/)

  if (quotedMatch) {
    return quotedMatch[1]
  }

  if (rawValue === "true") {
    return true
  }

  if (rawValue === "false") {
    return false
  }

  if (/^-?\d+$/.test(rawValue)) {
    return Number(rawValue)
  }

  return rawValue
}

function extractTitle(body: string, fileName: string) {
  const headingMatch = body.match(/^#\s+(.+)$/m)

  if (!headingMatch) {
    return titleFromFileName(fileName)
  }

  const cleanedHeading = stripMarkdown(headingMatch[1])
    .replace(/\s+guide\b.*$/i, "")
    .replace(/\s+\((Afenda|Vite|server-side).*\)$/i, "")
    .replace(/^[^\p{L}\p{N}]+/u, "")
    .trim()

  return cleanedHeading || titleFromFileName(fileName)
}

function extractDescription(body: string, title: string) {
  const narrativeBlocks = collectNarrativeBlocks(body)
  const candidates = narrativeBlocks
    .map((block) => summarizeNarrativeBlock(block))
    .filter(
      (candidate): candidate is SummaryCandidate => candidate !== undefined
    )
    .sort(
      (left, right) =>
        right.score - left.score || left.text.length - right.text.length
    )

  const bestCandidate = candidates[0]

  if (bestCandidate) {
    return bestCandidate.text
  }

  return buildFallbackDescription(title)
}

function extractStatus(body: string) {
  const statusPatterns = [
    /^\*\*Status:\*\*\s+\*\*([^*]+)\*\*/m,
    /^\*\*Status:\*\*\s+(.+)$/m,
    /^Status:\s+(.+)$/m,
  ]

  for (const pattern of statusPatterns) {
    const match = body.match(pattern)

    if (match?.[1]) {
      return stripMarkdown(match[1]).trim()
    }
  }

  return undefined
}

function isVisibleDocEntry(entry: DocEntry) {
  if (entry.hidden) {
    return false
  }

  return entry.docClass !== "historical-archive" && entry.docClass !== "delete"
}

function assertRequiredDocMetadata(
  entries: readonly DocEntry[],
  scope: string
) {
  for (const entry of entries) {
    const missingFields: string[] = []

    if (!entry.owner) {
      missingFields.push("owner")
    }
    if (!entry.truthStatus) {
      missingFields.push("truthStatus")
    }
    if (!entry.docClass) {
      missingFields.push("docClass")
    }
    if (!entry.relatedDomain) {
      missingFields.push("relatedDomain")
    }

    if (missingFields.length > 0) {
      throw new Error(
        `Missing required doc metadata for ${entry.relativeToDocs} in ${scope}: ${missingFields.join(", ")}`
      )
    }
  }
}

function sortEntries<T extends { order: number; title: string }>(
  entries: T[]
): T[] {
  return [...entries].sort(
    (left, right) =>
      left.order - right.order || left.title.localeCompare(right.title)
  )
}

function assertUniqueOrder(
  entries: Array<{ order: number; title: string }>,
  label: string
) {
  const seenOrders = new Map<number, string>()

  for (const entry of entries) {
    if (entry.order === 999) {
      continue
    }

    const previousTitle = seenOrders.get(entry.order)

    if (previousTitle) {
      throw new Error(
        `Duplicate order ${entry.order} in ${label}: "${previousTitle}" and "${entry.title}"`
      )
    }

    seenOrders.set(entry.order, entry.title)
  }
}

function assertUniqueTitles(entries: Array<{ title: string }>, label: string) {
  const seenTitles = new Map<string, string>()

  for (const entry of entries) {
    const normalizedTitle = entry.title.trim().toLowerCase()
    const previousTitle = seenTitles.get(normalizedTitle)

    if (previousTitle) {
      throw new Error(
        `Duplicate title "${entry.title}" in ${label}. Titles must be unique within a generated index.`
      )
    }

    seenTitles.set(normalizedTitle, entry.title)
  }
}

function assertNonEmptyDescriptions(entries: DocEntry[], label: string) {
  for (const entry of entries) {
    if (!entry.description.trim()) {
      throw new Error(
        `Empty description for ${entry.relativeToDocs} in ${label}. Add front matter or improve the source content.`
      )
    }
  }
}

function assertNonEmptyScriptDescriptions(
  entries: ScriptEntry[],
  label: string
) {
  for (const entry of entries) {
    if (!entry.description.trim()) {
      throw new Error(
        `Empty description for ${entry.fileName} in ${label}. Add a script override or improve the script header comment.`
      )
    }
  }
}

function assertDependencyCategoryConfiguration() {
  for (const category of DEPENDENCY_CATEGORY_ORDER) {
    if (!(category in DEPENDENCY_CATEGORY_LABELS)) {
      throw new Error(
        `Missing dependency category label for "${category}". Update DEPENDENCY_CATEGORY_LABELS.`
      )
    }
  }

  for (const category of Object.keys(DEPENDENCY_CATEGORY_LABELS)) {
    if (!DEPENDENCY_CATEGORY_SET.has(category)) {
      throw new Error(
        `Dependency category label "${category}" is not listed in DEPENDENCY_CATEGORY_ORDER.`
      )
    }
  }
}

function assertKnownDependencyCategory(category: string, relativePath: string) {
  if (!DEPENDENCY_CATEGORY_SET.has(category)) {
    throw new Error(
      `Unknown dependency category "${category}" in ${relativePath}. Allowed categories: ${DEPENDENCY_CATEGORY_ORDER.join(", ")}`
    )
  }
}

function renderTable(headers: string[], rows: string[][]) {
  const lines = [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
  ]

  for (const row of rows) {
    lines.push(`| ${row.map((cell) => escapeTableCell(cell)).join(" | ")} |`)
  }

  return lines.join("\n")
}

function formatLink(fromDirectory: string, targetPath: string, label: string) {
  return `[${label}](${relativeMarkdownPath(fromDirectory, targetPath)})`
}

function relativeMarkdownPath(fromDirectory: string, targetPath: string) {
  const relativePath = toPosixPath(path.relative(fromDirectory, targetPath))

  if (relativePath.startsWith(".")) {
    return relativePath
  }

  return `./${relativePath}`
}

function stripMarkdown(value: string) {
  return value
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/[*_~]/g, "")
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, "$1")
    .replace(/\s+/g, " ")
    .trim()
}

function escapeTableCell(value: string) {
  return value.replace(/\|/g, "\\|")
}

function toPosixPath(value: string) {
  return value.split(path.sep).join("/")
}

function toTitleCase(value: string) {
  return value
    .split(/[\s/_-]+/)
    .filter(Boolean)
    .map((token) => {
      const normalizedToken = token.toLowerCase()

      return (
        TITLE_EXCEPTIONS[normalizedToken] ??
        `${token.charAt(0).toUpperCase()}${token.slice(1)}`
      )
    })
    .join(" ")
}

function titleFromFileName(fileName: string) {
  return toTitleCase(fileName.replace(/\.md$/i, "").replace(/[-_]/g, " "))
}

function extractScriptDescription(content: string, title: string) {
  const leadingCommentMatch = content.match(/^\/\*\*([\s\S]*?)\*\//)

  if (leadingCommentMatch) {
    const commentLines = leadingCommentMatch[1]
      .split(/\r?\n/)
      .map((line) => line.replace(/^\s*\*\s?/, "").trim())
      .filter((line) => line && !line.startsWith("@"))

    const firstNarrativeLine = commentLines.find(
      (line) => !isLowSignalDescription(stripMarkdown(line))
    )

    if (firstNarrativeLine) {
      return clampDescription(stripMarkdown(firstNarrativeLine))
    }
  }

  return `Command-line utility for ${title}, maintained in the repository \`scripts/\` directory.`
}

function extractScriptRunCommand(content: string) {
  const runCommandMatch = content.match(/run with `([^`]+)`/i)

  return runCommandMatch?.[1]?.trim()
}

function collectNarrativeBlocks(body: string) {
  const lines = body.split(/\r?\n/)
  const blocks: NarrativeBlock[] = []
  let currentBlock: string[] = []
  let inCodeBlock = false
  let currentHeading: string | undefined
  let blockIndex = 0

  const pushCurrentBlock = () => {
    if (currentBlock.length === 0) {
      return
    }

    blocks.push({
      lines: currentBlock,
      heading: currentHeading,
      blockIndex,
      isNearTop: blockIndex < 2,
    })
    currentBlock = []
    blockIndex += 1
  }

  for (const line of lines) {
    const trimmed = line.trim()

    if (trimmed.startsWith("```")) {
      pushCurrentBlock()
      inCodeBlock = !inCodeBlock
      continue
    }

    if (inCodeBlock) {
      continue
    }

    if (!trimmed) {
      pushCurrentBlock()
      continue
    }

    if (/^#{1,6}\s+/.test(trimmed)) {
      pushCurrentBlock()
      currentHeading = stripMarkdown(trimmed.replace(/^#{1,6}\s+/, "")).trim()
      continue
    }

    if (trimmed === "---") {
      pushCurrentBlock()
      continue
    }

    currentBlock.push(line)
  }

  pushCurrentBlock()

  return blocks
}

function summarizeNarrativeBlock(
  block: NarrativeBlock
): SummaryCandidate | undefined {
  const trimmedLines = block.lines.map((line) => line.trim()).filter(Boolean)

  if (trimmedLines.length === 0 || isStructuralBlock(trimmedLines)) {
    return undefined
  }

  const normalizedText = stripMarkdown(trimmedLines.join(" ")).trim()

  if (!normalizedText || isLowSignalDescription(normalizedText)) {
    return undefined
  }

  const score = scoreSummaryCandidate(block, normalizedText)

  if (score <= 0) {
    return undefined
  }

  return {
    text: clampDescription(normalizedText),
    score,
    reason: inferSummaryReason(block),
  }
}

function isStructuralBlock(lines: string[]) {
  const structuralLineCount = lines.filter((line) =>
    isStructuralLine(line)
  ).length

  return structuralLineCount === lines.length
}

function isStructuralLine(line: string) {
  return (
    line.startsWith("#") ||
    line === "---" ||
    line.startsWith("|") ||
    line.startsWith(">") ||
    line.startsWith(":::") ||
    line.startsWith("<!--") ||
    /^[-*]\s/.test(line) ||
    /^\d+\.\s/.test(line) ||
    /^\*\*[^*]+:\*\*/.test(line)
  )
}

function isLowSignalDescription(value: string) {
  return (
    value.length < 20 ||
    /^(official documentation|related documentation|documentation readiness)\b/i.test(
      value
    ) ||
    /^(topic|read|scope|guide|collection|document)\b$/i.test(value)
  )
}

function clampDescription(value: string) {
  if (value.length <= MAX_DESCRIPTION_LENGTH) {
    return value
  }

  const sentences = value
    .split(/(?<=[.!?])\s+/)
    .map((sentence) => sentence.trim())
    .filter(Boolean)

  if (sentences.length === 0) {
    return value.slice(0, MAX_DESCRIPTION_LENGTH).trimEnd()
  }

  let description = ""

  for (const sentence of sentences) {
    const candidate = description ? `${description} ${sentence}` : sentence

    if (candidate.length > MAX_DESCRIPTION_LENGTH) {
      break
    }

    description = candidate

    if (description.length >= MIN_PREFERRED_DESCRIPTION_LENGTH) {
      break
    }
  }

  return description || value.slice(0, MAX_DESCRIPTION_LENGTH).trimEnd()
}

function buildFallbackDescription(title: string) {
  if (/auth/i.test(title)) {
    return `Project guidance for ${title}, including integration choices, security constraints, and implementation expectations.`
  }

  if (/api/i.test(title)) {
    return `Project guidance for ${title}, including contracts, route behavior, and implementation expectations.`
  }

  if (/database|drizzle|postgres/i.test(title)) {
    return `Project guidance for ${title}, including schema conventions, persistence concerns, and implementation expectations.`
  }

  if (/test|vitest/i.test(title)) {
    return `Project guidance for ${title}, including quality expectations, validation flow, and implementation conventions.`
  }

  return `Project guidance for ${title}, including conventions, references, and implementation expectations.`
}

function scoreSummaryCandidate(block: NarrativeBlock, text: string) {
  const heading = block.heading?.toLowerCase() ?? ""
  let score = 0

  if (!block.heading && block.blockIndex === 0) {
    score += 120
  } else if (block.isNearTop) {
    score += 30
  }

  if (heading.includes("how we use") || heading.includes("how we wire")) {
    score += 100
  } else if (heading.includes("map to")) {
    score += 80
  } else if (heading.includes("red flags")) {
    score += 35
  } else if (heading.includes("related documentation")) {
    score -= 100
  } else if (heading.includes("official documentation")) {
    score -= 80
  } else if (heading) {
    score += 20
  }

  if (containsUsefulDomainSignals(text)) {
    score += 25
  }

  if (text.length >= 60 && text.length <= 155) {
    score += 25
  } else if (text.length > MAX_DESCRIPTION_LENGTH) {
    score -= 10
  }

  if (/\b(not|never|avoid|only)\b/i.test(text)) {
    score += 10
  }

  if (/^\w+\s+guide\b/i.test(text)) {
    score -= 20
  }

  return score
}

function inferSummaryReason(block: NarrativeBlock): SummaryCandidate["reason"] {
  const heading = block.heading?.toLowerCase() ?? ""

  if (!block.heading && block.blockIndex === 0) {
    return "opening-paragraph"
  }

  if (heading.includes("how we use") || heading.includes("how we wire")) {
    return "how-we-use"
  }

  if (heading.includes("map to")) {
    return "map-to"
  }

  if (heading.includes("red flags")) {
    return "red-flags"
  }

  if (heading) {
    return "section-intro"
  }

  return "generic-block"
}

function containsUsefulDomainSignals(text: string) {
  return /\b(guidance|integration|conventions|implementation|auth|routing|validation|migration|server|client|state|deployment|testing|schema|permissions|security|api)\b/i.test(
    text
  )
}

async function writeIfChanged(filePath: string, nextContent: string) {
  const normalizedNextContent = await formatGeneratedContent(
    filePath,
    nextContent
  )
  const currentContent = await fs.readFile(filePath, "utf8").catch(() => "")

  if (currentContent === normalizedNextContent) {
    return
  }

  await fs.writeFile(filePath, normalizedNextContent, "utf8")
}

async function formatGeneratedContent(filePath: string, content: string) {
  if (path.extname(filePath).toLowerCase() !== ".md") {
    return content
  }

  const prettierConfig = await prettier.resolveConfig(filePath)

  return prettier.format(content, {
    ...prettierConfig,
    filepath: filePath,
  })
}

function withTrailingNewline(content: string) {
  return content.endsWith("\n") ? content : `${content}\n`
}

await main()
