import fs from "node:fs/promises"
import path from "node:path"

import {
  evaluateStorageGovernance,
  loadStorageGovernanceConfig,
} from "./lib/storage-governance.js"

const REPORT_PATH = path.resolve(
  "rules/storage-governance/storage-screening.md"
)

const config = loadStorageGovernanceConfig()
const evaluation = evaluateStorageGovernance(config)

const lines: string[] = [
  "# Storage Screening",
  "",
  "Generated by `pnpm run script:generate-storage-governance-report`.",
  "",
  "## Summary",
  "",
  `- Storage roots: ${String(evaluation.rootSummaries.length)}`,
  `- Violations: ${String(evaluation.violations.length)}`,
  "",
  "## Storage Roots",
  "",
]

for (const summary of evaluation.rootSummaries) {
  lines.push(
    `- \`${summary.root}\` : declared entries ${String(summary.entryCount)}, violations ${String(summary.violationCount)}`
  )
}

lines.push("", "## Violations", "")

if (evaluation.violations.length === 0) {
  lines.push("- No current storage-governance violations.")
} else {
  for (const violation of evaluation.violations) {
    lines.push(
      `- [${violation.rule}] \`${violation.path}\`: ${violation.message}`
    )
  }
}

await fs.writeFile(REPORT_PATH, `${lines.join("\n")}\n`, "utf8")
console.log(`Storage governance report written to ${REPORT_PATH}`)
