import { writeFile } from "node:fs/promises"
import path from "node:path"

import {
  evaluateGeneratedArtifactGovernance,
  loadGeneratedArtifactGovernanceConfig,
} from "./lib/generated-artifact-governance.js"

const outputPath = path.resolve(
  "rules/generated-artifact-governance/generated-artifact-screening.md"
)

const config = loadGeneratedArtifactGovernanceConfig()
const evaluation = evaluateGeneratedArtifactGovernance(config)

const lines: string[] = [
  "# Generated Artifact Screening",
  "",
  "Generated by `pnpm run script:generate-generated-artifact-governance-report`.",
  "",
  "## Summary",
  "",
  `- Governed roots: ${String(config.generatedRoots.length)}`,
  `- Violations: ${String(evaluation.violations.length)}`,
  "",
  "## Governed Roots",
  "",
]

for (const [index, root] of config.generatedRoots.entries()) {
  const summary = evaluation.rootSummaries[index]
  lines.push(
    `- \`${root.root}\` : max depth ${String(root.maxDirectoryDepth)}, allowed extensions [${root.allowedFileExtensions.join(", ")}], directories ${String(summary?.directoryCount ?? 0)}, files ${String(summary?.fileCount ?? 0)}, violations ${String(summary?.violationCount ?? 0)}`
  )
}

lines.push("", "## Violations", "")

if (evaluation.violations.length === 0) {
  lines.push("- No current violations under the generated artifact rollout.")
} else {
  for (const violation of evaluation.violations) {
    lines.push(
      `- [${violation.rule}] \`${violation.path}\` — ${violation.message}`
    )
  }
}

await writeFile(outputPath, `${lines.join("\n")}\n`, "utf8")

console.log(`Generated artifact governance report written to ${outputPath}`)
