import type { BillingPlan, BillingTier } from "./billing-plan.contract"

export const BILLING_PLAN_CATALOG: Readonly<Record<BillingTier, BillingPlan>> =
  {
    basic: {
      tier: "basic",
      name: "Basic",
      description: "For small teams starting with core operating workflows.",
      currencyCode: "VND",
      pricesMinor: {
        monthly: 990_000,
        quarterly: 2_670_000,
        yearly: 9_500_000,
      },
      features: [
        { key: "hrm", name: "Human Resources", included: true },
        { key: "crm", name: "Customer Relations", included: true },
        { key: "pm", name: "Project Management", included: true },
        { key: "excel_ai", name: "Excel AI", included: true },
        { key: "accounting", name: "Accounting", included: false },
        { key: "mrp", name: "Manufacturing", included: false },
        { key: "ecommerce", name: "E-commerce", included: false },
        { key: "ai_copilot", name: "AI Copilot", included: false },
        { key: "sdk", name: "Developer SDK", included: false },
      ],
      limits: {
        maxUsers: 10,
        maxStorageGB: 5,
        maxApiCallsPerMonth: 10_000,
        maxAiTokensPerMonth: 100_000,
        maxInvoicesPerMonth: 50,
        maxProducts: 100,
        maxOrdersPerMonth: 0,
        maxStorefronts: 0,
        maxWebhooks: 3,
        customDomain: false,
        sla: "99.5%",
        support: "email",
      },
      modules: ["hrm", "crm", "pm", "excel-ai"],
    },
    pro: {
      tier: "pro",
      name: "Professional",
      description:
        "For growing operators who need deeper back-office coverage.",
      currencyCode: "VND",
      pricesMinor: {
        monthly: 2_990_000,
        quarterly: 8_070_000,
        yearly: 28_700_000,
      },
      features: [
        { key: "hrm", name: "Human Resources", included: true },
        { key: "crm", name: "Customer Relations", included: true },
        { key: "pm", name: "Project Management", included: true },
        { key: "excel_ai", name: "Excel AI", included: true },
        { key: "accounting", name: "Accounting", included: true },
        { key: "mrp", name: "Manufacturing", included: true },
        { key: "otb", name: "OTB Planning", included: true },
        { key: "tpm", name: "TPM", included: true },
        { key: "ecommerce", name: "E-commerce", included: false },
        { key: "ai_copilot", name: "AI Copilot", included: false },
        { key: "sdk", name: "Developer SDK", included: false },
      ],
      limits: {
        maxUsers: 50,
        maxStorageGB: 50,
        maxApiCallsPerMonth: 100_000,
        maxAiTokensPerMonth: 500_000,
        maxInvoicesPerMonth: 500,
        maxProducts: 5_000,
        maxOrdersPerMonth: 0,
        maxStorefronts: 0,
        maxWebhooks: 10,
        customDomain: false,
        sla: "99.9%",
        support: "priority",
      },
      modules: [
        "hrm",
        "crm",
        "pm",
        "excel-ai",
        "accounting",
        "mrp",
        "otb",
        "tpm",
      ],
    },
    enterprise: {
      tier: "enterprise",
      name: "Enterprise",
      description:
        "For organizations that need full capability, deeper support, and custom domain posture.",
      currencyCode: "VND",
      pricesMinor: {
        monthly: 7_990_000,
        quarterly: 21_570_000,
        yearly: 76_700_000,
      },
      features: [
        { key: "hrm", name: "Human Resources", included: true },
        { key: "crm", name: "Customer Relations", included: true },
        { key: "pm", name: "Project Management", included: true },
        { key: "excel_ai", name: "Excel AI", included: true },
        { key: "accounting", name: "Accounting", included: true },
        { key: "mrp", name: "Manufacturing", included: true },
        { key: "otb", name: "OTB Planning", included: true },
        { key: "tpm", name: "TPM", included: true },
        { key: "ecommerce", name: "E-commerce", included: true },
        { key: "ai_copilot", name: "AI Copilot", included: true },
        { key: "sdk", name: "Developer SDK", included: true },
        { key: "ifrs", name: "IFRS Reporting", included: true },
      ],
      limits: {
        maxUsers: -1,
        maxStorageGB: 500,
        maxApiCallsPerMonth: 1_000_000,
        maxAiTokensPerMonth: 5_000_000,
        maxInvoicesPerMonth: -1,
        maxProducts: -1,
        maxOrdersPerMonth: -1,
        maxStorefronts: 10,
        maxWebhooks: 50,
        customDomain: true,
        sla: "99.95%",
        support: "dedicated",
      },
      modules: [
        "hrm",
        "crm",
        "pm",
        "excel-ai",
        "accounting",
        "mrp",
        "otb",
        "tpm",
        "ecommerce",
        "ai-copilot",
        "sdk",
        "ifrs",
        "admin",
      ],
    },
  }

export function getBillingPlan(tier: BillingTier): BillingPlan {
  return BILLING_PLAN_CATALOG[tier]
}
